<?php
namespace Lifeline\Controller;

use stdClass;
use WC_Product_Attribute;
use WC_Product_Simple;
use WC_Tax;
use WP_Query;

class LifelineSync extends LifelineConnector {
    const SYNC_TYPE_CRON = 1;
    const SYNC_TYPE_WP_CRON = 2;
    const SYNC_TYPE_MANUAL = 3;
    const SYNC_TYPE_UNKNOWN = 4;

    protected $limit = 100; 
    protected $helper;
    protected $log_file;

    protected $tax_classes = [
        '18' => 'standard',
        '10' => 'reduced-rate',
        '5' => 'low-rate',
        '0' => 'zero-rate'
    ];

    public function __construct() {
        parent::__construct();

        $this->helper = new LifelineHelper();
    }
    
    public function mark_for_web() {
        $sql = "UPDATE artikli
                SET orig_sifra = 'WEB'
                WHERE public.artikli.naziv IN ('^AJ CRATECOR filter 20 x 2gr','^aj DETOX MIX','^AJ DETSKI filter 20 x 1.5gr','VICHY Liftactive Supreme дневна крема за сува до многу сува кожа 50ml','80713-NIVEA FRESH COMFORT intimna nega i higiena 250ml','VICHY Liftactive Supreme ноќна крема за сите типови на кожа 50ml','ABRI MAN PREMIUM X14','ABRI-FLEX L3 PREMIUMX14','ACC 600mg 10eff.(acetylcysteinum)','ACC DIRECT KESI 10X 600 mg','ACC JUNIOR 200mg/ml sol 100ml','ND PHYTOSOLUTION GEL 400ML','ACEROLA 30tbl x 500mg -bls','ACEROLA tbl.30 x 40mg-blister','VICHY SLOW AGE CREAM','ACETON 100ml','ACIDI BORICI PULVIS 30 gr','VICHY Dermablend корективна пудра за сите типови на кожа № 25','ACIDI BORICI sol. 3% 1000 ml','VICHY Dermablend корективна пудра за сите типови на кожа № 35','ACIDOSALUS sprej','AD3 voden rast. kapki 10ml- IVAFARM','AKTIVEN JAGLEN CAPS. X 10','VICHY LIFTACTIV SPECIALIST GLYCO-C NIGHT PEEL- ампули за хиперпигментација и свеж изглед на кожата, за сите типови на кожа','ALANERV cps. 20x 920mg','VICHY Liftactive Supreme H.A Epidermic Filler серум за нега за сите типови кожа 30ml','ALFAPLAST water rezist.ass.5vel /40','VICHY MINERALBLEND 06 30ML','ALGA SAN AKUT GENU mast za koleno 50ML','VICHY MINERALBLEND 09 30ML','ALGA SAN MOBIL GEL za masaza 100ML','ALGA SAN MOBIL krem 50ml.','ALITOL perli.x 48','ALKALAX tbl. 20 x 5mg','ALKAVIT folic acid film.obl.tbl.20 x 5 mg','ALKAVIT folic acid tbl.30 x 0,4 mg','SEBAMED BABY krem ekstra mek 50 ml','ALPECIN COFEIN C1 sampon','SEBAMED BABY krem protiv osip 100 ml','ALVOGEN ORS sum.tbl x 12','SEBAMED BABY krem za lice 50 ml','ALWAYS INFINITY 10 pads.','ALWAYS INFINITY 12 pads.','SEBAMED BABY losion 200 ml','ALWAYS PLATINUM NIGHT vloski/6 -101421','SEBAMED BABY sampon 150 ml','ALWAYS PLATINUM NORMAL vloski/8 -101419','SEBAMED BABY sapun 100gr.','ALWAYS PLATINUM SUPER vloski/7 -101420','ALWAYS ULTRA NIGHT DUO vloski 2x7/14 - 101402','SEBAMED CF gel protiv akni 10 ml','ALWAYS ULTRA NORMAL DUO X 20 - 101368','SEBAMED CF tonirana krema za akni 10 ml','ALWAYS ULTRA SUPER vloski /8 - 101427','SEBAMED CF pena za lice 150 ml','AMOSVITAL ACE+ZN+C EFF x 20','AMOSVITAL MG. FORTE 240 mg sum.tbl.','SEBAMED CF sapun 100gr.','AMOSVITAL PIVSKI KVASEC+A+C+E tbl.x500','AMOSVITAL VIT.C 300mg+CINK 5mg x 60cps','SEBAMED CF tonik za lice 150 ml','ANDOL 100 tbl. 20 x 100 mg','SEBAMED shampon perut 200 ml','ANGAL pastili x 24','ANGAL sprej 30ml.','ANTIMETIL tbl x 30','ANTINIKOTEA filter rezervi','Подхранувачки супер калциум во прав-10','Супер калциум за деца во прав-10','Супер калциум со лецитин-20 капсули','Кордицепс-100 капсули','Хитосан-100 капсули','Спирулина-100 капсули','Приспивни дуо-60 таблети','Масло од лук-60 капсули','Мултифункционален уред-биоенергија','Мултифункционален уред-фрижидер','Здрава перница','Здрава прекривка','Здрав душек','AQUA MARIS GTT 10 ML','AQUA MARIS kesi morska sol x 30','AQUA MARIS plus 30 ml','AQUA MARIS -SET- za ispiranje na nos','AQUA MARIS sprej 30 ml','AQUA MARIS STRONG spray 30 ml','AROMA krem ARGAN 75ML','AROMA krem NEVEN 75ml','AROMA krem ZDRAVJE 30g','AROMA krem/KOKOS ekstrakt 75ml','AROMA KREMA EKSTRAKT KOKOS I GLICERIN','ARTICOKA SOK 200 ML','ARTRO TABL. X 30 DEVA','Антилипиден чај-40 кесички','ASPIRIN 500 tbl. 20 x 500 mg','Цинк-60 капсули','ASPIRIN PROTECT 100 MG X 30 TABL','Дигест-90 таблети','ASPIRIN PROTECT 100 tbl.x56','Женски хигиенски влошки','ASSO krema za nega na race 100 ml','ASSO/Maslinka krem za race 100ml','ASTERA CETKA AKTIV MEDIUM 1+1','ASTERA DETSKA CETKA ZA ZABI mix','ASTERA PASTA PARADONT ACTIVE 75 ML','ASTERA PASTA PARADONT STOP 75ml.','AUBE FILER protiv brchki na lice 10ml','AUBE SERUM - NOKEN za koza na lice 30ml','AUBE SERUM za dnevna hidratacija 15ml','AURIGEN fisek za hig.na uvo','AVARICON cps.x 30','AVARICON gel 75 ml','AVENT SCF222/20 LAZLIVKA 0-6m/maska','AVENT SCF651/27 NATURAL SILIKONSKA CUCLA (0+M) 2/1','AVENT SCF695/17 SISE NATURAL PLASTICNO 0% BPA 260ml.-PLAVO','AVENT SCF704/00 GOLEMA CHINIJA 12m+','AVENT SCF751/07 (6+m) CHASHA SO KLUN ROZEVA 200ml','AVENT SCF753/00 CASA SO KLUN 260ml. (12+M)','AVENT SCF755/00 CASA SO KLUN 340ml 18+','AVENT SCF796/01 (9+m) CHASHA SO CEVKA 200ml MASHKA','B.N 12220 SILIK. CUCLA ZA SISE MILK 0-3MES. SIROKO GRLO','B.N 28140 LATEX CUCLA LAZLIVKA 6-18MES.','B.N.31150 IGRACKA MAG.OSUMKA','B.N.31246 MUZICKA IGRACKA','B.N.31507 GRICKALKA za zabi- PEPERUTKA','B.N.34122 LANCE','B.N.34155 DEKORIRANO LANCE ZA CU','B.N.39301 VES.SILIKONSKI BRADAVICI * 2','B.N.46000 DEK.POLIPROPILENT SISE','B.N.47000 DEK.POLIPROPILEN.SISE','BABY CARE CALMING vl.mar/63','BABY CARE FRESH vl.mar/63','BABY CARE SENSITIVE vl.mar /63','BABYTOL D3 + K1 X 30 KAPSULI SO TECNOST','BABYTOL D3 X 30 CAPS 4U','BABYTOL D3+ OMEGA x 30 cps','BABYTOL DHA + OMEGA x 30cps','B-COMPLEX drag x 60','B-COMPLEX obl.tbl. x 30','BEBELAN VL.MARAMICI X 24 ROZE','BEBELAN VL.MARAMICI X 24 ZELENI','BEBELAN VODA 0.5 L','BEBELAN VODA 0.5ML','BEBELAN VODA 1.5L ZA DECA','BEBEVITA 19052 banana-jabolko 90gr','BEBIVITA 1403 multi ovoshje 90g','BEBIVITA 19052 banana/jabolko 90g','BECUTAN KIDS VITs anticolic sol.30ml','BECUTAN KIDS VITs aspirator za nos','BECUTAN KIDS VITs isotonic nasal psray 30ml','BECUTAN KIDS VITs sir. OMEGA 3 250ml','BECUTAN krema za deca 100ml','BECUTAN krema za deca 50ml','BECUTAN kupka 200ml','BECUTAN kupka so kamilica 200ml','BECUTAN kupka za deca 400ml','BECUTAN MASLENA KUPKA 150ml','BECUTAN maslo od lavanda 200ml','BECUTAN maslo za deca 200ml','BECUTAN mleko za deca 200ml','BECUTAN PENA za race/lice 250ml','BECUTAN podlogi(novi) 60 x 90cm/7','BECUTAN pudra za deca 100gr','BECUTAN sampon so kamilica 200ml','BECUTAN sampon za deca 400ml','BECUTAN sampon/kupka 2 vo 1 200ml','BECUTAN sampon+kupka 400ml','BECUTAN SAPUN 90 gr','BECUTAN vitaminska mast 200ml','BECUTAN vitaminska mast 100ml','BECUTAN vitaminska mast 50ml','BECUTAN vlazni maramici /20','BECUTAN vlazni maramici /26','BECUTAN vlazni maramici /72','BEDOXIN tbl. 20 x 20 mg','Belmiran SAN 20tbl','SYNERGY FERROFECT x30 tbl','BEPANTHEN BABY ung. 5% 30 g','SYNERGY VIT.D3 2000iu cps x30','BETADINE r-r 100 ml (1%)','SYNERGY VITAMIN K 80mg','BETADINE vag. 14 x 200 mg','BETAPLAST plast. flaster 5m x 2,5cm','BETTY BLAZNICI 80 PARCINJA','BETTY FLASTER SENSITIV X 14','BEVIPLEX N granuli 70 gr','BILOBIL cps.x 60','BILOBIL FORTE cps. 80 mg x 20','BILOBIL INTENSE cps. 60x120mg','BILOBIL INTENSE cps.20 x 120mg','BIO GELEE ROYALE MEDEX FORTE amp.x 12','BIO LIFE-100% Maslo od Kokos 200ml','BIOASTIN cps. 4 mg x 60','BIOBLAS arganovo maslo 100ml','BIOBLAS maska+regenerator 2 vo1 200 ml','BIOBLAS ORGANIC kopriva maslo shampon 400ml 3-10118','BIOBLAS ORGANIC lovorovo maslo shamp.400 ML','BIOBLAS ORGANIC maslinovo/konj.opavche shamp. 400ml 3-9937','BIOBLAS SHAMPON KOKOS ORGANSKI 360ml','BIOBLAS SHAMPON SO ORGANSKI ARAGAN 360ml','BIOBLAS shampon/farbana kosa 400 ML','BIODERMA ATODERM huile de douche 1L- MASLO ZA TUSHIRANJE','BIODERMA CICABIO krem 40ML','BIODERMA CICABIO/ARNICA krem 40ML','BIODERMA HYDRABIO crem 50ml','BIODERMA HYDRABIO SERUM 40ml','H. AID HAIR-VIT cps.x 30','H-AID METHYLCOBALAMIN B12 tbl. x 60','H-AID OMEGA 3-6-9 cps. x 60','BIODERMA SEBIUM hydra krem 40ML.','H-AID PROSTAVITAL cps. x 30','H-AID VITAMIN B99 COMPLEX tbl. x60','H-AID LIVERCARE tbl. X 60','H-AID MAGCITRA tbl. X 60','H-AID OMEGAZON cps. x 30','H-AID OSTEOVIT tbl. x 60','H-AID RED YEAST rice tbl. x 90','BIODERMA-ATODERM INTENSIVE BAUME 500ML','H-AID TEA TREE OIL sapun 100g','H-AID VITAMIN D3 1000 i.u spray','BIODERMA-CICABIO LOTION SPRAY 40ML','H-AID VITAMIN E maslo 100% 50ml','H-AID VITAMIN E sapun 100g','H-AID WHEAT GERM OIL cps. x 60','BIODERMA-SENSIBIO GEL MOUSSANT 200ML','BIOGAIA KAPKI 5ML.','BIOGAIA LIMON tbl. za dvakanje x 10','BIOKRILL ACTIV blister X 30 CAPS','BIONIKA UREA 40% crem50g','BIOSEPT gel za dezinfekcija 500 ml','BIOSEPT gel za dezinfekcija 90 ml','BIOXET lenti za depil. za MAZI x 20 3-8303-1','BIOXSIN ACNIUM conc.gel 15ml','BIOXSIN ACNIUM krem 30ml','BIOXSIN ACNIUM maska 75ml','BIOXSIN MELA TON conc.gel 15ml','BIOXSIN MELA TON gel za piling 180ml','BIOXSIN MELA TON toniran krem 30ml','BIOXSINE DERMAGEN FORTE shampon 300ml 3-9338','BIOXSINE DERMAGEN PENA 150ml 3-7671','BIOXSINE DERMAGIN SERUM 15X10ml','BIOXSINE DERMAGEN shampon/masna kosa 300ml 3-9336','BIOXSINE DERMAGEN shampon/suva/normalna kosa 300ml 3-10301','BIOXSINE DERMAGEN ZENI sham./suva/normalna 300ml 3-9269','BIOXSINE DERMAGEN ZENI shamp.za farbana kosa 300ml 3-9437','BIOXSINE TBL x 40','BI-VITAMIN C 1000 EFF.X 20 BIOFAR','BI-ZINC+VITAMIN C eff.X 20 BIOFAR','NU-ASHWAGANDHA caps. 90 x 450mg','NU-MAGNEZIUM CITRAT caps. X 90','NU-NAC 600mg','NU-SELENIUM tbl. 100 x 100mcg','NU-SERRAZIMES caps. x 90','NU-VITAMIN D3 1000 IE x 180 soft caps.','NU-VITAMIN K2 100 mcg','BOROLA ENTAN cps. x 30- BLISTER','NU-VIT.D3 10.000 IU','NU-CHOLINE & INOSITOL caps. x 100','NU-COQ10 caps. 50 x 100mg','NU-INULIN PRASHOK 227gr.','BRONLES DIREKT per. r-r 15 x 750mg/5ml 30 x 375 mg','BRONLES SIR 250ML/5ML','BRONLES sirup 150 ml (125 mg/5 ml)','BRUFEN Kesi 600 mg x 30 sum.granuli','BRUFEN sirup 100mg / 5ml','BRUSNICA CAJ 100 gr','BS.ELAST.ZAVOJ ( 4.,5mX12cm)','CAFFETIN COLD MAX PRASOK SO LIMON X 10','CAFFETIN COLD plus tbl.x 10','CAFFETIN COLD tbl. 10','CAFFETIN tbl. 12 x 500 mg','CAILLOU SIRUP 20 X 5ML SPOON','CAJ ALKALAX MIX FILTER','CAJ ALKALAX REFUS 50G','CAJ BECUTAN anason 20 x 5 gr','CAJ BECUTAN ANASON 200gr','CAJ BECUTAN anason/kamilica 20 x 5gr','CAJ BECUTAN DETSKI ZA DOBRA NOK 200gr','CAJ BEL SLEZ 50G REFUS','CAJ BRUSNICA filter 20 x 2gr','CAJ HIBISKUS FILTER X 20KESI','Anthelios XL Dry Touch Anti-Shine- Крема со заштитен фактор 50+ против масен сјај на лицето','CAJ KAMILICA REFUS 25G','CAJ KANTARION filter 20 x 1,5 g','CAJ KIRKOLINA LUX x 20kesi','ANTHELIOS SUN INTOLERANCE Крема за лице со Невросензин за дневна превенција на реакции на кожата предизвикани од сонцето','CAJ LINCURA 50gr','CAJ MAGDONOS filter 20 x 2gr','CAJ MATOCINA FILTER X 20','CAJ NATURAVITA UVIN H -granuli 180 gr','CAJ PLANINSKI filter 20 x 1,5gr','CAJ PROTIV VOSPALENIE NA JAJNICI 100gr','CAJ SIPKA SO HIBISKUS filer 20 x 2,5 gr','CAJ UVE MIX 100 gr','Hydraphase Intense Riche-Интезивна рехидратантна нега за сува и чувствителна кожа','CAJ VALERIAN MIX filter 20 x 2g','CAJ ZALFIJA 25gr','CAJ ZELEN filter 20 x 1,5gr','CALIVITA vit.C 1000mg.','CANBEBE 4 (7-18kg peleni)/10','CANBEBE 5 (11-18 kg peleni) / 8','CANBEBE 5 (11-18kg)/ 32','CANBEBE 6 (15+ kg peleni) / 8','CANBEBE 6 (16+kg peleni)/ 36','CANPED 60 x 90 / 10 podmetaci za vozrasni','CANPED LARGE peleni za vozrasni/16','CANPED PEL. MEDIUM X 18','CS ANTI DARK SPOT 50+ 50ml','CAREFREE ALOE sek. vloski /58 - 12070037','VICHY Liftactive Supreme дневна нега за сите типови на кожа со заштитен фактор 30 50ml','CAREFREE ULTRA NOKNI PLUS/10-12080014','CAREFREE ULTRA SUPER PLUS/10- 12080013','MINERAL 89 50ML + LIFTACTIV FRESH','CASA ZA FECES Sterilna','CASA ZA URINA STERILNA (ASTR)','CEPKALKI BABI SO GRANICNIK SEPTONA','CERUSTOP SPRAY 10ML','VICHY MINERAL BLEND 03 30ml','CHYMORAL tbl. x 30','Cicaplast Levres- Балзам за обновување на иритираните и испукани усни','CINKVITAMINSKA MAST 50G','CITIKOL B sol. 10ml.','VICHY Mineral Micellar Milk for dry skin 400ml','COLG.HERBAL NEPCA(GUMS) pasta za zabi 75 ml.','COLGATE cetka 360 SO BATERIJA - 22010085','COLGATE cetka DETSKA 2-6 god EXTRA SOFT- 22010036','COLGATE cetka SMILES 6+ -SOFT- 22010037','COLGATE HERBAL ORIGINAL 75 ML','COLGATE KONEC za zabi 25m','UR-XEMOSE BABY BALSAM PROTIV CESANJE 200ml','COLGATE pasta 6+ SMILES JUNIOR 50ML-22020087','COLGATE pasta JAGLEN- NATURAL EXTRACTS 75ml','COLGATE pasta MAX WHITE EXPERT COMLETE + cetka SONIC- 22020399','COLGATE pasta TRIPLE ACTION 2897/ 50 ml-22020003','COLGATE PASTA ZA ZABI PROPOLIS 100 ML','URI.CU-ZN BEBE sprej 100ml','COLGATE pasta za zabi SMJLS 3-5 g','COLGATE PASTA ZA ZABI WHITENING 100 ML','COLGATE PLAX complete care 500ml','COLIEF sol 7 ml','CONTRACTUBEX gel 20g','COREGA BIO tbl.x 30','COREGA EXTRA STRONG KREM 40G','COREGA PARTS tbl.x 30','COSINUS spray','COSINUS tblx30','COUNTERPAIN CREM 100GR.','CRYSTAL VISION lubrikant 10ml','CURAPROX 1560 soft cetka za zabi','CURAPROX 1560/3 pack soft cetki za zabi','CURAPROX 3960 super soft cetka za zabi','CURAPROX 3960/3 pack super soft cetki za zabi','CURAPROX 5460 ultra soft cetka za zabi','CURAPROX 5460/3 pack ultra soft cetki za zabi','CURAPROX 5460-ORTHO cetka za zabi','CURAPROX BLACK IS WHITE SET PASTA +CETKA CS5460','CURAPROX CTC 203- cistach na jazik','CURAPROX DF 834 konec 50m','CURAPROX SMART-ULTRA SOFT CETKA','DAIPERS 16+kg peleni /40','DAIPERS 4-10 kg peleni /56','DAIPERS 7-18 kg peleni /50','DALERON 120/5 SIR.','BD FOTODERM KID SPF50 + SPRAY','DANAI BADEM krema 200 ml +PAVLODERM','DEFENDYL SIR. 120 ML','DENTIPUR tbl REFIL','BIODERMA ATODERM SOS SPREJ 50ml','DERMOGAL losion za lice 120 ml','DESDERMAN gel za dezinfekcija 100 ml','DESDERMAN PURE 100ml','DETSKA VIT.KREMA-PAVLOV.100ml','DETSKA VIT.KREMA-PAVLOV.250ml','DEZINTAL RAZREDEN R-R 0.2% 950 ml','DIABIL CAPS. BIONIKA','ANTH LOTION SPF30+ ECOTUB 250ML','DIASTOP PROBIO CPS X 10','DIAVRON TABL. X 30','ANTH LOTION SPF50+ ECOTUBE 250ML','DIET.FEROHEL RASTVOR','DIET.GINKO OMEGA+B-compleks cps.x 30','DIET.IMMUNO SHARK cps.x 30','DIET.JABOLKOV OCET cps.x 60','DIET.MAGNEZIUM NOK cps.x20+10 gratis','DIET.MAKULIN cps x 30','DIET.MAKULIN PLUS tbl.x 30','DIET.REHIDROMIKS MALINA x 5','DISCREET DEO IRRESISTIBLE (CRNI)sek.vloski/20-102141','DISCREET DEO WATERLILY X20 vloski','DISCREET IRRESISTIBLE vloski/60 - 102152','DISCREET NORMAL (rozevi) sek.vloski-102126','DISCREET NORMAL PLUS vloski/60 -102153','DISCREET SPRING BREEZE vloski /20-102121','DISCREET SPRING BREEZE vloski/60 -102154','DISCREET WATERLILY vloski /20-102129','DISCREET WATERLILY vloski/60 -102156','D-MANNURO brusnica kesi x13','DOC ALOE VERA limon 250ml/L','DOC COENZIM Q10 x30tbl','DOC COLAGEN 250ml oral sol.','DOC COLAGEN 250ml set 1+1 PROMO','DOC HAIR x 30tbl','DOC HYALURONIC 50ml oral sol.','DOC HYALURONIC 50ml SET 1+1 PROMO','DOC MAGNESIUM 300mg x 60tbl','DOC MASTIC 175mg x60mg','DOC MULTIVITAMIN MAN 30tbl','DOC MULTIVITAMIN WOMEN 30tbl','DOC NADURAL sir.adulti 200ml','DOC NATURAL sirup kids 200ml','DOC VIT. C 500mg x 30tbl','DOC VITAMIN B-COMPLEX 30tbl.','DOC.M-SAMPON za voski 75 ml','DOCTORS ANTISTRI BALZAM 200ML','DOCTOR''S dzeben inhalator','DOCTOR''S FE x 4 tamponi za usi silikonski','DOCTORS MASKA ZA VOZRASNI','DOCTOR''S M-SPRAY za voski 100 ml','DOCTOR''S sapun ANTIDANDRUF-SULFUR','DOCTOR''S sapun ANTIEGZEMA-KATRAN','DOCTOR''S sapun ANTIINFECTION-EUKALIPTUS','DOCTORS SAPUN MEDICINE','DOCTOR''S tamponi penesti za ushi x 2','DR. PLANT TIMJAN prasok za noze 100g','DR.HAUSCHKA maska za revitalizacija 30ml','DR.LEO D3+DHA OMEGA cps.30x100mg','dr.t. intact bomboni malina','DR.THEISS EUKALIPTUS C balsam 50 gr','DR.THEISS BRSHLEN sir. 100ML','DR.THEISS DOBRA NOK - tegavec sir. 100ml','DR.THEISS HERBALSEPT KIDS PROTIV KASLICA X6','DR.THEISS HERBALSEPT LIZAVCINJA GRLO X 6','DR.THEISS INTACT -crzna ribizla/17','DR.THEISS INTACT -jabolko/17','DR.THEISS INTACT -kapina /17','DR.THEISS INTACT-borovinka I jogurt /17','DR.THEISS LACALUT krema za fiks.prot.','DR.THEISS MUCOPLANT mor.voda naz.sprej 20 ml','DR.THEISS MUCOPLANT mor.voda so ehinacea i eukaliptus naz.sprej 20 ml','DR.THEISS TEGAVEC I EHINACEA sirup 100 ml','DR.THEISS TEGAVEC sirup 100 ml','DR.THEISS TEGAVEC sirup 250 ml','DR.THEISS VENEN gel 100ml','DR.THEISS ZA VENI gel 125 ml.+25% gratis','DR.VITON Magnezan B6 x30drg','DR.VITON Magnezan NEURO x30tbl','DR.VITON MOVENS tbl x 24','DR.VITON OMEGA-3 +vit.E+D3 x60caps','DR.VITON VIT. C serum za lice 30ml','DR.WOLZ DARMFLORA cps x 4','DR.WOLZ DARMFLORA PLUS pulv.35gr','DR.WOLZ IMMUNOKOMPLEX 250ml','DR.WOLZ SELEN ACE cps.60 x 100 mcg','DR.WOLZ VITAMIN D3 1000IE cps.x 60','DR.WOLZ ZELL OXYGEN PLUS 250ml','DRASANVI VIT .D3 4000IE','DUOBIOTIK cps.x 10','URI. BARIESUN SPF 30 KREM 50ML','DUREX CLASSIC/3 prezerv.','URI. BARIESUN SPF 50 PUDRA SVETLA','DUREX PLAY KLASIK LUBRICANT 50ml','URIAGE TERMALNA VODA duo set 300ml.','DUREX SENSITIVE/3 prezerv.','ECOMER cardio cpsx60','URIAGE ROLL-ON 3 ACTIVE X 2','URI. EAU TERM. KREMA ZA RACE 50ML X 2','ELAKSA cps. x 20','URI. BARIEDERM CICA SERUM 30ML','ELMEX cetka ULTRA SOFT x3','ELMEX pasta KARIES 75 ml','ELMEX pasta SENSITIVE 75ml','ELMEX tecnost za usta KARIES 400ml','VICHY Dercos Anti-dandruff','ERBA VITA CALMA BABY sirup 150 ml','ERBA VITA HAPPY AGE cps X60','ERBA VITA LIEVIT B12 cps.60 x 510 mg','BD FOTODERM NUDE TOUCH SPF50+ 40ml','ESI - CAJNO DRVO MASLO 20ml','ESI ALOE VERA GEL 100 ml (+vit.E +chajno drvo)','BD FOTODERM AR TONIRAN KREM SPF50+ 30ml','ESI ALOE VERA JUICE 1 l','ESI CAJNO DRVO maslo 25 ml','ESI CRANBERRY CYST kesicki x 16','ESI DRIMO 100 gr','ESI ECHINAID cps. x30','ESI ERBAVEN FRESH gel 100 ml','ESI ERBAVEN RETARD cps. X30','ESI GINKOMAX tbl. x30','ESI KARBOFIN FORTE cps.x 30','ESI LE DIECI ERBE tbl.x 40','ESI MELATONIN tbl.120 x 1mg','ESI MELATONIN tbl.30 x 1mg','ESI MULTICOMPLEX ADULTI tbl. x30','ESI MULTICOMPLEX JUNIOR tbl. x50','ESI MULTICOMPLEX SENIOR tbl. x30','ESI NO DOL cps. x60','ESI NO DOL krema 100 ml','ESI NORMOLIP 5 cps. X30','ESI Pid block losion sprey','ESI PID BLOCK samp.200ml','ESI PROPOLAID 33% alkoholen rastvor 50 ml','ESI PROPOLAID bezalkoholen rastvor 50 ml','ESI Propolgola forte spray 20 ml','Anthelios ULTRA SPF 50+ Водоотпорна крема за лице со заштитен фактор 50+','ESI PSYLLIOX ACTIV FIBRA kesicki x20','ESI VITAMIN C PURA 1000MG X 30TBL','ESSENSAL FOSFOLIPIDY CAPS. X 40','Мицеларна вода ULTRA - реактивна кожа','ETERICNO MASLO CAJNO DRVO 10ML','EUC.63003 PH5 losion 400 ml','EUC.63122 PH5 maslo za tus. 400 ml','EUC.63382 EDS UREA 5% reg.krem za race 75ml.','EUC.63924 HYALURON FILLER norm.koza dneven krem 50ml','EUC.63997 3 vo 1 cleanser 200ml','VICHY Deo Mineral ролон сет 1+1 100ml','VICHY Capital Soleil Mattifying 3-in-1 SPF 50 50ML','VICHY C S Fresh Protective Milk SPF 50','EUC.88786 ROLL ON 0% AL.50ml','Capital Soleil Gentle Protective Milk Kids SPF 50 300 ml','EUCERIN 63141 PH5 sapun 100 gr','EUCERIN 63485 hialuron filer dn.krem 50ml','EUCERIN 63486 hialuron filer nok.krem 50ml','EUC-SET KIDS LOTION SPF 30+ 150ML','EVA MENOFIX FLASTERI X1','EVERY DAY MAXI NIGHT FRESH hiper/10- 0604 (700929)','EVERY DAY MAXI NIGHT sensitive/10- 1837 (701271)','EVERY DAY NORMAL FRESH hiper/10 -0600 (702697','EVERY DAY SENSITIVE NORMAL ultra plus/10 -1898 (12701269)','EVERY DAY SENSITIVE SUPER ultra plus/18 +neseser0395 (703143)','EVERY DAY SUPER AKTIV vloski /10- 1807 (700908)','EVERY DAY SUPER FRESH economy/18 -0614 (700922)','FEMIBION 1 tbl x 30','DR.HAUSCHKA Krem od rozi 30ml','DR.HAUSCHKA TONIK ZA LICE SPECIJALEN 100ML','FERVEX adults kese x 8','FERVEX sugar free kesicki x 8','FILTRI ZA MASKA N99 X2','FITALP gel 50 ml','FITALP INHALATOR i kapki','FLASTER ALFAPLAST 1,25cm X5m TEKSTILEN','FLASTER BETAPORE hart. 5m x 1,25cm','FLASTER BETAPORE hart. 5m x 2.5cm','FLASTER SANPLAST 5cm x 5m','FLEXOFYTOL X60','FLOGOCID MAST 50G','FLONIVIN PLUS caps. x 10','FOLACID x 120tbl - HEALTHY LIFE','FOLNA KISELINA tbl. 20 x 5 mg','FORTELAX sirup 75 ml','FORTRANS kesicki 4 x 64 g','FORVITA A,C,E + SE tbl.x 30','FORVITA ANTI-STRESS tbl.x 30','FORVITA AVIREX caps.x60 (d3+zn+b12)','FORVITA B-KOMPLEX TBL.X 500','FORVITA D3 4000 IE tbl.x100','FORVITA KIDS D3 tbl.90 x 400 IE','FORVITA vit. C tbl. 30x 1000mg','BIODERMA-SEBIUM NIGHT PEEL 40ML','FUTROLI za ochila','BIODERMA SENSIBIO RICH krem 40ml','GAMIBETAL tbl.500mg x20','VICHY Capital Soleil UV-AGE DAILY воден флуид против фото-стареење UVB SPF 50+ и UVA PF 46','GARNIER COLOR NATURALS. 660','GARNIER FARBA NATURALS 110','GARNIER FARBA NATURALS 9.1','GASTAL tbl. x 24','VICHY Dercos Anti-Dandruff Deep Purifying Shampoo','GAVEZ GEL 100ml','TETE KUPKA PENLIVA ZIMSKA NEZNOST 420ML','TETESEPT DOZA BLAGODARNOST','TETESEPT GEL KREAM HELLO BEAUTY','TETESEPT GUSARSKA AVANTURA','TETESEPT HELLO HAPPINESS','GAZA ZLOZENEC 5x8sm/10','TETESEPT HELLO WINTERCARE','TETESEPT HELLO WINTERHEART','GEL ZA DEZINFEKCIJA DESDERMAN 500ml','TETESEPT KUPKA BACK WARM BATH','TETESEPT KUPKA BRONCHIALBATH','GERMANIUM 132+NAT cps. 60X500mg','TETESEPT KUPKA DEEP RELAX','TETESEPT KUPKA INDISKA AJUVEDA','GINGIVAL GEL NBF NANO 30g','TETESEPT KUPKA JOINT&amp;MUSCLE','TETESEPT KUPKA KAPENJE HOKUS POKUS','GLYCEROLUM 50 ml','TETESEPT KUPKA MALA SIRENA','TETESEPT KUPKA MALI RAZBOJNICI','GYNEX 4 vag.x 10','TETESEPT KUPKA MUSCLE RELAX','GYNEX FORTE vag.x 10','TETESEPT KUPKA ORIENTAL','TETESEPT KUPKA PENLIVA IGRA NA DOZD','TETESEPT KUPKA PENLIVA ZIMSKA MAGIJA 420ML','TETESEPT KUPKI SET 3X20ML','TETESEPT MAL ASTRONAUT','TETESEPT MOJ EDNOROG','H. AID BETA GLUCAN( 1:3/1:6) x 30cps','TETESEPT POTRAGA PO BOGATSTVO','TETESEPT SET KUPKI','TETESEPT SOL ZA KAPENJE ANTISTRES','TETESEPT SOL ZA KAPENJE BACK&amp;SHOULDER 600G','H. AID COENZIM Q10 200mg x 30cps','TETESEPT SOL ZA KAPENJE COLD RELIEF 600G','TETESEPT SOL ZA KAPENJE DEEP RELAXATION 600G','TETESEPT SOL ZA KAPENJE JOINTS&amp;MUSCLES 600G','TETESEPT SOL ZA KAPENJE MALKU SREKJA','TETESEPT SOL ZA KAPENJE PARCE LJUBOV','TETESEPT TAJNATA NA KLEOPATRA','TETESEPT VREME ZA ODMOR','TETESEPT VULKANSKI SVET','H. AID MENOVITAL tbl.x 60','H. AID NEUROFORTE tbl.x 30','H. AID PREGNAZON complete cps.x 60','H. AID PREGNAZON tbl. x 30','H. AID SERRAPEPTASE 60000 iu cps.x 30','H. AID SEXOVIT forte tbl.x 30','H. AID SPIRULINA 500mg x 60tbl','H. AID vit. B12 1000 mcg sprej 20ml','H. AID VITAMIN C1000x30tbl.','H. AID V-VEIN tbl. x 60','H. AID ZINCOVIT C tbl.x 60','H. NATURA maslo DIVO ORIGANO 10 ml','H. NATURA maslo GJUMBIR 10ml','H. NATURA maslo GREJPFRUT 10ml','H. NATURA maslo KAJSIJA SEMKI 20ml','H.A SELENIUM TBL. 60 X 200MCG.','HAPPY ANTIBAKTERISKI MARAMICI','HARTIKOL 30 CAPS PHARMAS','HA-ZINC GLUCONATE TAB. 90 X 70MG','HEMOROL mast 35 gr','HERBA BREZA sampon 1000 ml','HERBA KAMILICA sampon 1000 ml','HERBA KOPRIVA sampon 1000 ml','HERBIFIT VENOGEL gel 75ml','HERBIKO K2D3 caps. x 20','HERBION BRSLEN sirup 150 ml','HERBION ISLANDSKI LISAJ sirup 150 ml','HERBION JAGLIKA sirup 150 ml','HERBION PASTILI BRSHLEN 16X35 mg','HERBION TEGAVEC sirup 150 ml','HERPESAN gel 7 gr','HIP 3600 Caj komoraca x20kesi','HIP.6143 TELESKI OBROK 190gr.','HIP.6250 PILE so oriz i zel.190 gr','HIPERMANGAN KRISTALI 5G','HIPERMANGAN sol. 1% 100 ml','HIPP - 8508 JABOLKO/BANANA/BISKVIT 100G','HIPP VODA 1.5 l 8089','HIPP 2036 COMBIOTIC 2 300g','DR. HAUSCHKA hidratantna dnevna krema 30ml','HIPP 2300 -ORS 200 RAST.ZA REHIDR 200 ml.','HIPP 2840 BEBI PCENKA 200 gr','HIPP 2951 BEBI ORIZ kasha 250 gr.','HIPP 30405 multi grain 100 % 200gr.','HIPP- 3644 caj od komoraca 15x0.36 kesi','HIPP 4010/906 MORKOV kasa 125 gr.','BD FOTODERM MINERAL SPF50+','HIPP 4063 BABY TIKVA kasa 125 gr.','HIPP 4202-PRASKA kasa 125 gr.','HIPP 4203 -SUMSKO OVOSJE I JABOLK kasa 125 gr.','HIPP 4210 JABOLKO I BANANA kasa 125 gr.','HIPP 4212 KAJSIJA kasa 125 gr.','HIPP 4233-02 JABOLKO kasa 125 gr.','HIPP 4236 banana/krusha/mango 125g','HIPP 42502 kalinka/acerola/jab/malina 100g','HIPP 4253-SLIVI kasa 125 gr.','HIPP 4300 KRUSA VILJAMOVKA kasa 190 gr.','HIPP 4320 KRUSHA/JABOLKO kasha 125g','HIPP 4420 sliva, jabolko, praska kasa 190ml','HIPP 4702 INT.ZIT,KAJS,JAB,OVES kasa 190 gr.','HIPP 4800-INTEG. zIT. SO MEsANO OVOsJE kasa 190 gr.','HIPP 5509 GRIZ/JABOLKO/PRASKA KASA','HIPP 5512 NOKNA/GRIZ/BANANA 190G','HIPP 5513 NOKNA KAKAO/BANANA 190G','HIPP 5515NOKNA GRIZ 190G','HIPP 5516 Nokna 7 zitarki 190g','HIPP 6105 MORKOV SO KOMPIR I LOSOS kasa 190gr','HIPP 6123 JAGNESHKO SO MORKOV I KOMPIR kasa 190 gr.','HIPP 6153-TELESHKO/ZELENCUK I KOMPIRI kasa 190 gr.','HIPP 6200 PCHENKA/KOMP. I MISIRKA kasa 190 gr.','HIPP 6230 SPAGETI BOLONEZE kasa 190 gr','HIPP 6250-PILESHKO/ORIZ I ZELENCUK kasa 190 gr.','HIPP 6280-01 MORKOV/PCENKA/TELESKO kasa 190gr','HIPP 8523-02 BAN,KRUSA,MANGO kasa 100gr','HIPP 8602-01 PRASKA/BANA/JAB.OLKO kasha 120g','HIPP 90106 SHAMPON ZA RASCESHLUVANJE 200ml','HIPP 9560 BABY sampon 200 ml','HIPP 9580 BABY losion 350 ml','HIPP 9648 spf 50+ krem za lice 30ml','HIPP CAJ KOMORAC filter kes.30g (3600)','HIPP-8040 JAB.I MORKOV sok 200 ml.','HIPP-9551 KUPKA ZA DOBRA NOK 350ML','HIPP-9620 BABY krema 75 ml','WELEDA detski gel za zabi 50ml.','HIPPIS 8606-01 SPORT mango/banana/port/krusha/oves 120g','HIRURSHKI KAPI so lastik/250','WELEDA citrus dezodorans 100ml','HN-MASLO OD CRNO SEME 125ML.','HYDROGEN 3% 100 ml','HYDROGEN 3% spray 120 ml','HYDROGEN 9% 100 ml OBICEN','ANTHELIOS XL wet gel за мокра или сува кожа со многу висока заштита','208c1aba-f403-4730-b0be-079917700071','HYDROGEN sol. 3% 1000 ml','ANTH. WET GEL KIDS 250ML','HYGIA sampon 120 ml (1 g/100 g)','VICHY cis dry touch fluid 50spf 50ml','HYLO-COMOD sol.10ml','HYLO-GEL 10ml','VICHY C S Fresh Protective Milk SPF30+ 300ml','IBUPROFEN AKTIV krem 10% 50gr','IBURAMIN COLD sir.100ml','IBURAMIN COLD tbl. 12x200mg','IBUTOP KREM 100gr.','IBUTOP KREM 50gr','ICE POWER COLD gel 75ml','ICE POWER COLD PLUS MSM gel 200ml','ICE POWER COLD spray 200ml','ICHTIOLI mast 30 gr','ICHTIOLNA mast 25 ml','IDEOS tbl.30 x (500MG+400IE)','IGLA 0,45 x 16 mm/100 (ASTR)','IGLA 0,6 x 30 mm/100 23G','IGLA 0,7 x 40 mm/100 (ASTR)','IGLA 0,8 x 40 mm/100 21G (ASTR)','IGLA 0.45 X 13mm - KDM','IGLA 0.5X16 X 100','INFACALM OIL','IMMUNO AHCC','IMMUNOZINK susp.100ml','IMUNIX soft cps.x 30','IMUNOBETA GLUKAN CAPS.X30','IRIDIUM GAZA za nega na oci x 20','ISLA CASSIS LOZANGES x 30','ISLA MINT LOZANGES x 30','ISLA MOSS LOZANGES x 30','ISLANDSKI LISAJ sirup 150 ml','ISOMAR BABY SPRAY isotonic 30ml','ISOMAR HIPERTONIC VIALS 18X5ml','ISOMAR ISOT.SPRAY NOS UVO 100ml','ISOMAR sol. ZA OCI MULTIDOSE 10ml','ISOPRINOSINE 500 MG * 50','ISOPRINOSINE SIR.50/150ML','JAKE MINTS -pepermint bomboni','JAM-VITAMIN C 1000MG','JAM-ZINK+VIT C+D3 PASTILIX30','JASMIN SOFT blaznici,vata x70','JECODERM mast 25 gr','JECORIS OL.BANANA 500ML','JECORIS OLEUM LIMUN 500 ml','JOHN.BABY sampon 500 ml +250 ml gratis','JOHNSON BABY sampon 300 ml-NOV','JOHNSON BABY Shampon 750ML so pumpa (500+250ml)-NOV','JOHNSON BEDTIME losion 300 ml','JOHNSON KONDICIONER SVETKAVI KAPKI vo spray 200ML','JONSON sampon kamilica 750nl NOV','KALJACHI za chevli x 100','KALJACI OD NETKAEN TEKSTIL X 100','Kalmfleks 100 g krem','KAMAGEL gel 40 gr','KAMEN ZA PETI','KANOIL 7% CBD 10 ML','KANOIL BIO SPRAY 12% 10ml','KANOIL MAST 100mgCBD - 50g','KANTARION krema 45 ml','KANTARION vag. x7','VICHY Ideal Soleil Solar Protective Water Spf 50 200 ml','KAPI BOUFFANT beli so lastik /100','KESI ZA URINA DETSKI (ASTR)','KETOKONAZOL sampon 100ml','KHAN TIGROV krem-gel 200ml','KHAN TIGROVA mast 30 ml','KILIBARNA OGRLICA ZA BEBE','KLOMPI MUBB - 160102','KM-DIGITALEN TOPLOMER BK4301','KM-KN95 ZASTITNA MASKA X 10','KM-PULSOKSIMETAR C101A2','KONSKI BALZAM 500ML','KOPRIVA seme 100 gr.','KOPRIVA SOL. 30ML ALKALOID LILA','KREM 48 za race 100ml','KRSAC za tableti','KUTIJA za lekovi dnevna','KUTIJA ZA MASKA CASE (classic)','KUTIJA ZA MASKA TENKA','LABELLINO-85299 coconut water & aloe vera','LACALUT CARIES PROTECT PASTA','LACALUT cetka AKTIV za zabi','LACALUT cetka DETSKA 4+ god.','LACALUT cetka SENSITIVE za zabi','LACALUT cetka WHITE za zabi','LACALUT FLORA pasta +cetka gratis 75ml','LACALUT FLORA RASTVOR 300ML','LACALUT konec za zabi 50m','LACALUT L -interdentalna cetka za zabi','LACALUT M -interdentalna cetka za zabi','LACALUT MICELAREN MULTIEFEKT RASTVOR 500ml','LACALUT MICELAREN RASTVOR SENSITIV 500ml','LACALUT MICELAREN TARTAR RASTVOR 500ml','LACALUT MICELAREN VAJTENING RASTVOR 500ml','LACALUT MULTI EFEKT PASTA 75ML. +cetka gratis','LACALUT pasta AKTIV 75ml','LACALUT pasta AKTIV 75ml+gratis cetka','LACALUT pasta DETSKA 4-8 god','LACALUT pasta DETSKA 8+ god.','LACALUT pasta DETSKA 8+/+ PLAK r-r KIDS 50ml','LACALUT pasta SENSITIV 75ml','LACALUT r-r AKTIV 250ml','LACALUT r-r SENSITIVE 250 ml','LACALUT S -interdentalna cetka za zabi','LACALUT SENSITIVE GENTLE WHITE PASTA','LACALUT WHITE REPAIR PASTA','LACALUT XS -interdentalna cetka za zabi','LACALUT XXS -interdentalna cetka za zabi','LACTIL ORGANIC CAPS. X 56','LACTOGYN capsX15','LACTOGYN intimen gel 50gr.','LACTOGYN intimen tec.sapun 250ml.','LACTOGYN vag.cps x7','LARA BEBI STAPCINJA X200','LARA MARAMICI CLASSIC X 72','LARA MARAMICI XXL X 120 SO KAPAK','LARA X 15 ANTIBAKTERISKI MARAMICI','LEA ANTIRID za oci krema 20 ml','LEA BADEMOVO maslo 50 ml - FITOFARM','LEA BYE BYE CELLULITE KREM 250 ml','LEA CICKOVO maslo 50 ml - FITOFARM','LEA Eter.maslo ruzmarin 10 ml','LEA HERBAL losion so cajno drvo/ANTIAKNE 130ml.','LEA HIDRANTNA dnevna krema 50 ml','LEA HRANLIVA nokna krema 50 ml','Vichy Capital Soleil Solar-Protective Water-SPF-30-Hydrating','LEA HYDROGEN MLECEN 9% 100ML','LEA KANTARIONOVO maslo 50 ml - FITOFARM','LEA KOKOSOVO maslo 50ML','LEA krem Q10, goji i vit.E 50ml','LEA LAVANDA eter.maslo 10 ml','LEA losion za cist.lice 200 ml','LEA NEVENOVO maslo 50 ml - FITOFARM','LEA pr.pegi I fleki krema 50 ml','LEA RICINUSUVO maslo 50 ml','LEA SPECIJALNA pr.stareenje na koza krema 50 ml','LEA SUN KIDS mleko posle soncanje 200 ml','LEA SUN mleko za posle sonc. 200 ml','LEA SUN SPF 30 mleko 200 ml','LEA-MAMMA priroden lanolin za bradavici 30ml','lepenki za ochi - detski','LIBRESSE 8817 CIKL.MAXI NORMAL/10 - 37010049','LIBRESSE 8956 CLASSIC NORMAL DUO vloski /20','LIBRESSE 8957 CLASSIC SUPER DUO vloski /18-37010004','LIDERA deo krema 50 ml','LIDERA krema za noze 50 ml','LINEX BABY DROPS','LINEX COMPLEX cpsx14','LINEX FORTE cps.x 14','LINEX JUNIOR kesicki x 10','LISTERINE ADVANCE WHITE','LISTERINE COOL MINT 250ml','ABSOLUTE DRY DAB-ON 35ML','LISTERINE FRESH BURST 500ML','OLIOVITA BALZAM 10ml','LISTERINE TOTAL CARE ZERO 500ml','LISTERINE WHITENING 500ML','LIVSANE ANTIALER.LOZENGI X24','LIVSANE BABY SENSITIVE vl.maram./80','LIVSANE BRUSNICA plus x 30cps','LIVSANE CAJ BEL SLEZ REFUS','SET SENSIBIO AR BB SENSIBIO GEL MOUSSANT','LIVSANE CAJ BRUSNICA 30% FILTER','LIVSANE CAJ GJUMBIR FILTER','LIVSANE CAJ KAMILICA FILTER','LIVSANE CAJ KANTARION FILTER','LIVSANE CAJ MATOCINA FILTER','LIVSANE CAJ SENA','LIVSANE CAJ ZELEN NEFERM. FILTER','LIVSANE caj zimska bajka filterx20','LIVSANE eff. CALCIUM x 20','LIVSANE eff. MAGNESIUM 500mg x 20','LIVSANE eff. MAGNESIUM x 20','LIVSANE HOT BERRIES X 10 KESICKI','LIVSANE HOT GINGER+MED+LIMUN X 10','LIVSANE HOT LEMON x 20','LIVSANE IMMUNE SUPPORT AMP.7X25ML','LIVSANE ISLANDSKI LISHAJ pastili x 40','LIVSANE kosa/nokti kapsuli x 60','LIVSANE maramici x10','LIVSANE napitok za kaslica x20kesi','LIVSANE pulv.MAGNESIUM CITRAT direkt/30kesi','LIVSANE vloshki za GRADI x 30','LIVSANE ZINK+HISTIDIN+CYSTEIN x 40tbl','LOBELLO BISKVIT 5 ZITARICI 200gr- 54091','SET SENSITIV MICELARNA+LIPIKAR 400ML','LOBELLO BISKVIT BEZ GLUTEN 250mg - 54090','SET MIC.WATER+LIPIKAR GEL 400ML','LUNERBA tbl x 30','LUVALYC cps x 30','LYCOPEN+VIT.E cps.30 x (300+10)mg','LYSOBACT spray PEPERMINT 30ml','LYSOBACT za zvakanje tbl. 30 x (20 mg + 10 mg)','BDFOTODERM MAX SPRAY SPF50+ 400ml','MAGNESIUM 400mg+B-complex/20pulv -ALKALOID','MAGNESIUM KRKA 300mg x 20kesi','MAGNESIUM tbl 150 x 250mg','BD FOTODERM SPRAY SPF30+ 400 ml','MALTEKS JACMENOV SLAD 920 gr.','MARAMICI PALOMA 10X10BR.','MARISOL FRESH SPREY 50ml','BD PHOTODERM BRONZE SPF50+','MARISOL ISOTONIC sprej za nos 50 ml.','BD PHOTODERM MAX TONIR.KR.SPF50+','MARISOL PANTHENOL sprej za nos 50 ml','BD PHOTODERM MAX ULTRA FLUID 50+','MASKA FFP N95','MASKA N99 SINA - DETSKA VENTIL','BD PHOTODERM SENS.SPF50+ 100 ml','MASKA N99 ZOLTA - DETSKA VENTIL','MASKA NOVA PRATKA','MASKA ROZEVA DETSKA KH-90','EMBRYOLISSE MICELAREN LOSION 250ML','EMBRYOLISSE CREME CONCENTRE 75ML','EMBRYOLISSE LAIT CREME SENSITIVE','MAST OD KONOP LADNO 100ML','EMBRYOLISSE HYDRA MAT','MAST OD KONOP ZA ZAGREVANJE 100ML','EMBRYOLISSE HYDRA SERUM 30ML','MEDEX GELEE ROYALE cps x30','EMBRYOLISSE GLOBAL ANTI AGE CREAM','MEDEX GELEE ROYALE x 40cps.','MEDICAL ANTIBAK.gel 400 ml','MEDICAL GEL za suvo mienje 75 ml','EMBRYOLISSE RADIENT EYE','EMBRYOLISSE LASHES &amp; BROWS 6.5ML','MELEM BEOGRADSKI 40ml','MELEM za usni 4,5gr.','MENNEN COOL WAIT speed stick deo gel 85 gr','MERALYS 0.05% sprej za nos 2024-04-22T20:02:07.945501986Z 10ml','MERALYS 0.1% sprej za nos 10ml','MERALYS COMB SPRAY 10ML','MERALYS spray HA 0.5mg/ml. 10ml.','MERALYS spray HA 1mg/ml. 10ml.','MERZ SPECIAL drg.x 60','METAFEN tbl. x 10','MIKROKLIZMI EASYLAX ZA DECA 6 x 3gr','MIKROKLIZMI EASYLAX ZA VOZRASNI X6','MINOTIK sol 10ml','MOLLERS COD LIVER LIMUN 250ml.','MOLLERS COLD LIVER TUTI FRUTI 250ml','MOVENS KREM 100 ml','MRL-CHAGA tbl 90 x 500mg','MRL-CORIOLUS tbl 90 x 500mg','MRL-HERICIUM tbl.90 x 500mg','MRL-MAITAKE tbl. 90 x 500mg','MULTI ESSENCE VIT.+ADULTI 50+ TBL.X30','MULTI ESSENCE VIT.+MINERALI TBL.X30','MULTI ESSENCE VITAM I MINERALI KESI X30','MULTIVITAMINSKI SANOSTOL sirup 230ml','MUSTELA 2 vo 1 KOSA I TELO sampon 200 ml','MUSTELA DETSKI sampon 200 ml','MUSTELA HIDRANTNO mleko za telo 300 ml','VICHY Dermablend корективна пудра за сите типови на кожа № 20','MUSTELA zast.vitam.krema 50ml.','MY BABY gel za nepca 7ml','VICHY Dermablend корективна пудра за сите типови на кожа № 30','N.ESS ARTICHOKA cps.50X350mg','N.ESS COENZIM Q10 cps.30X30mg','N.WEALTH Ca+Mg+Zn tbl.x 100','N.WEALTH OMEGA 3-6-9 cps.x 60','NAIL CARE CISTI PRIRODNI NOKTI','NAILNER LAK 2vo 1 15ml -protiv gabicki','NALGESIN FORTE tbl.20 x 550 mg.','NALGESIN S tbl. 10 x 275 mg','NASALEZE PM SHIELD SPRAY','NASALEZE-cold and flu blocker spray','NASALEZE-SPREJ ZA ALERGII','NAUSOLVIT JUNIOR 6M+ SOL. 20ML','NELIT ELEKTROLIT ORS (1sc=3kesi)','NEOFEN PLUS gel 50gr','NEUROBION amp.3X3ml','NEUROBION FORTE drg. x 20','NEURO-VIT X 30TBL REPLEK','NEUROVITAL FORTE tbl. x 30','NEVEN krema 150 ml DANAI','ROSE VALLIS ANTI AGE NOKJNA KREMA','NISITA SPREY 20ml. za nos','ROSA VALLIS MICELARNA VODA 250ML','NIVEA 45+ DNEVEN KREM PROTIV BRCKI za zategnuvanje na koza','ROSA VALISS ANTI AGE DNEVNA KREMA','NIVEA BABY KAMILICA sampon 200 ml','INN-D-MANOZIN KESIX10','NIVEA BABY PUDRA 100 GR','INN-D-MANOZINN PROTECT KESIX10','NIVEA BLACK&WHITE INVISIBILE rolon MAZI 50ML','INN-GRAMINN CAPS.X30','NIVEA BLACK&WHITE ULTIMATE IMPACT rolon MAZI 50ML','INN-GRAMINN SUPP.X10','NIVEA CARE & DIAMOND krem-maslo za tusiranje 250ml','NIVEA CARE & STAR FRUIT gel za tusiranje 250ml','INN-LONGUPINN SPRAY 50ml','NIVEA CREME 250ML','INN-LUPRINN CAPS.X30','NIVEA FRESH BLOSSOM 48h protection 150ml','INN-MIOCYSTINN FERTILE KESIX20','NIVEA KREM mleko 250 ml','INN-NATTOKINN CAPS.X30','NIVEA LEMONGRAS&OIL SAPUN 100GR','NIVEA MEN DEEP shaving foam 200ml','INN-R-LIPOINN CAPS.30X150mg','NIVEA MEN SENSITIVE RECOVERY pena za bricenje','NIVEA MEN SENSITIVE shaving gel 200ml','INN-SERAPINN CAPS.30X60000IE','NIVEA MILD pena za bric.200 ml','NIVEA mleko 250 ml -80201','INN-SPERGININN Q10 TBL.X16','NIVEA PROTECT&CARE shower gel MEN 250ML','NIVEA Q10 LOSION ZA TELO 200ML','NIVEA Q10 POWER anti-wrinkle+firming NOKEN KREM protiv brcki','NIVEA Q10+ anti-wrinkle SPF 15 DNEVNA KREMA proriv brcki','NIVEA Q10+C anti-wrinkle&energy cream 50ml','NIVEA SILVER PROTECT gel za bric.200 ml','NIVEA SOFT krema 100 ml','NIVEA SOFT krema 200 ml','NIVEA SOFT krema 50 ml','BABE- STOP AKN PURIFYING CLEANSING GEL 200ML','NOGRIPIN FORTE tbl','BABE- STOP AKN MATTIFYING MOISTURISER 50ML','NOKSIR BUBA','NOVOLAX film obl.tbl. 30 x 5 mg','BABE- STOP AKN KERATOLYTIC FLUID 30ML','NUA NUA CRNA PASTA+GRATIS CETKA','BABE- PEDIATRIC SUNSCREEN WET SKIN SPF50 200ML','NU-BETA 1,3/1,6 D-GLUCAN CAPS.90 X 100 mg','BABE- PEDIATRIC EXTRA MILD SHAMPOO 200ML','NU-DHA KIDS CHEWABLE caps.x 60','BABE- PEDIATRIC CRADLE CAP SHAMPOO 200ML','BABE- HA+ MULTI REJUVENATING BOOSTER 50ML','NUK 701150 LATEX 0-6m/1M CUCLA ZA SISHE','BABE- HA+ MULTI PROTECTOR CREAM SPF30 50ML','NUK 713153 6+/2M LATEX CUCLA ZA SISHE','BABE- HA+ EYES AND LIPS TENSOR MULTI CORRECTOR 15ML','NUK743517 0-6M/1M SILIKON SISHE VINI PU SINO 150ML','NUK750404 ACTIV CUP SHISHE 12+ SILIKON 300ML','BABE- FACE SUNSCREEN SUPER FLUID SPF50 50ML','NU-LIQUID VIT.D3 400IU / 4KAPKI 59ML','NU-L-OPTI ZINC CAPS 100 X 30MG','BABE- FACE ESS SOOTHING MICELLAR GEL 245ML','NUT-BROMELAIN x60tbl','NUT-CLEANSE formula 7 x14 tbl','BABE- FACE ESS HYDRONOURSHING CREAM SPF20 50ML','NUT-NATUREL SLEEP x60cps','NUTRINO-BEZMLECNA KASA 200G','BABE- FACE ESS HYDRO 24H REACTIVE SKIN 50ML','NUTRINO-jabolka i borovnica 125g','BABE- BODY OIL SOAP 500ML','NUTRINO-jabolko,praska,jagoda,malina 100gr','BABE- BODY ALOE VERA 300ML','820.125','NUTRINO-misirka, brokula, pavlaka, oriz 190g','BABE- BODY 10% UREA REPAIRING LOTION 500ML','NUTRINO-ovosh.miks so zit.pire 100 gr- 20% popust','NUTRINO-praska,oriz 190gr','NUTRINO-prva tikvicka 80gr','NUTRINO-prvo morkovce 80gr.pire od zelencuk','NUTRINO-telesko so zelencuk i pavlaka 190gr','NUTRINO-tikva, pavlaka, oriz 125g','NU-VIT.D3 1000 LIQ.30ML EXTRA','OB TAMPONI ProComfort MINI X 8','OCHILA - so korektivni stakla','OCTENISEPT (0,1 g + 2 g) 50 ml','OCUHYL C sol 10ml','OLIGOGAL Cr cps. x 30','OLIGOGAL SE cps.x 30','OLIGOGL-ZN+VIT.C.CPS.30X(15+60)MG','OLIGOVIT tbl.x 30','OMEGA 3 PHARMA VITAL 1000mg+vit.E','OPERIL P sol. 10 ml (0,025%)','OPERIL P sprej 10 ml (0,025%)','OPERIL sol. 10 ml (0,05%)','OPERIL sprej 10 ml (0,05%)','OPTIC bioluteina 25x30tbl','OPTIFREE Rastvor za Leki 355 ml (*ALCO)','ORAL B ESSENTIAL zaben konec 50 m','ORALSEPT r-r 100 ml (1,5 mg/ml)','ORALSEPT spray 0.15% 30ml','OREGAMAR ORIGANO x 15cps- MARNYS','OSTEO K2 tbl.x 60','OSTEOACTIV FORTE SUM.TBL. 20X1000MG','URIAGE BARIESUN CREM SPF50+','PAMPERS 1 (2-5kg) /43','UR-189-BARIESUN 100 SPF50+','PAMPERS aktiv 5 (11-16)/22','PAMPERS JAMBO 2 (3-6kg)/94','PAMPERS JAMBO 4 (9-14kg)/70','PAMPERS JAMBO 6(13-18)/52 - 4483','PAMPERS jumbo 2 (4-8kg)/94-NOVI','PAMPERS MIDI 3 (6-10kg)/ 20- NOVI','PAMPERS sensitive vl.maram. 6x52 -4532','PAMPERS vl.maramici fresh 6x52','PANTENE 3vo1 shampon-REPAIR i PROTECT 300ml','PANTENE maska color protect/201897','PANTENE maska protect hidration/201896','PANTENE maska repear protect/201895','PANTENE maska superfood/201941','PANTENOL krem 30gr','PANTENOL mast 30 g','PANTENOL RASTVOR 5% 125ml','PANTENOL sprej + R-OR 5% 100 ml','PANTEXOL krema 25 gr','PANTEXOL mast 25 gr','PARACETAMOL supp. 10 x 300 mg','PARAFINKO MASLO 500ML GALAFARM','PARAFINSKO maslo 10 ml (FIT)','PARAFINSKO maslo 100 ml','PARAFINSKO maslo 100 ml (GALA)','PARAFINSKO maslo 1000 ml','PARODONTAX CLASSIC pasta 75ml','PARODONTAX FLUORID pasta 75ml','PARODONTAX ULTRACLEAN pasta 75ml','PARUSAN tonik za zeni 200 ml','PARUSAN sampon za zeni 200 ml','PAVLOVICEVA ORIGINALNA mast 100 ml','PAVLOVICEVA so peru balsam mast 50 ml (FITOFARM)','PEDACET sampon protiv voski 60ml','PELIKAN hanzaplast x10','PERSEN FORTE cps.','PERSKINDOL COOL GEL 100ml.','PFERDEBALSAM ZELEN BALSAM 250ml- BONES','PFERDEBALSAM CRVEN STRONG 250ml - konjski balsam','PFERDEBALSAM ZELEN BALSAM 500ml- BONES','PHARMADOKT cupalka','PHLEBODIA film obl.tbl. 15 x 600 mg','PHYSIO MICELL SOL SENS 200ML','PICO LAX SIRUP 150 ML','PICO MULTIVIT GTT 12ML','PIKOVIT forte 7+ tbl.x 30','PIKOVIT pastili 4+ x 30','PIKOVIT sirup 150 ml','PILFUD losion 1 x 60 ml (5%)','PIVSKI KVASEC BETAVITEVIT tbl x 40','PLIVIT C tbl. 250 x 500 mg','PLIVIT C tbl. 30 x 50 mg','PLIVIT C tbl. 500 mg x 60','PM-GINKOMED cps.30 x 100mg','PM-UROGOLD CAJ filter x 20','POTASSIUM-U sol 10ml','POX CLIN PENA 100 ML','PREMAMA duo 30 tbl','PRIMULA sirup 120 gr','PROAFTOL sprej','PROANGI sprej','PROBALANS cps. x 20','PROBEBI BRONHI sol. 10 ml','PROBIO CHOCO+C+Zn X 20 TBL ZA ZVAKANJE 4U PHARMA','PROBIOTIC FORTE caps. x 10','PROBOTALIFE BABY ORIGANO NASAL sol 10ml.','PROBOTALIFE BABY ORIGANO NASAL spray 30ml','PROBOTALIFE HYPERTONIC ORIGANO NASAL spray 30ml.','PROBOTALIFE origano maslo 10ml.','PROBOTALIFE SEPTL ORIGANO sprej za usta 30ml','PROBRONHI sol.','PROCULIN CPS X 30','PROCULIN LENS CARE r-r za leki 400ml','PROCULIN R-R ZA LEKI - TRAVEL 100 ML','PROCULIN sol. 10 ml (0,3 mg + 15 mg)/ml','PROCULIN Tears ADVANCE 10ml','PROGASTAL sol.','PROLIFE cps.x 20','PROLIFE ENZIMI cps x 30','PROLIFE pastili x 24','PROLIFE sol.7 x 10 ml','PROLIFE VIS susp. 7x8ml','PROPOBAZA GEL. 20 ML','PROPOLIS 5% bezalh.r-r za deca 15 ml','PROPOLIS DENTALEN gel za deca 20ml.','PROPOLIS DENTALEN gel za vozrasni 20ml.','PROPOLIS SPREJ za usta 30ml.','PROSPAN sirup 100 ml','PROSTAMAX CPS. X30','PROSTAMIN 30tbl.','PROSTAPIL cps.X30','PROTECT GEL ANTISEPTIC 75ML','PVC TALK S pregledni rakavici','RAID sprej za letecki insekti 400 ml','RAKAVICI M BEZ TALK NITRILNI X300','RAKAVICI L LATEX LOW POWDERED X 100','RAKAVICI -L latex so talk x100','RAKAVICI L SO TALK IRONSKIN X100','RAKAVICI- L so talk X100','RAKAVICI -M latex so talk x100','RAKAVICI M SO TALK IRONSKIN X100','RAKAVICI -M so talk x100','RAKAVICI MYGUARD - L x 100','RAKAVICI MYGUARD - M x 100','RAKAVICI NITRILNI BEZ TALK L X100','RAKAVICI NOVI L','RAKAVICI SAFEPLUS- S-bez talk x 100','RAKAVICI TALK S LATEX X 100','RAKAVICI ZENSE BEZ TALK LATEKS M X 100','RAKAVICI ZENSE L BEZ TALK X 100','RAPIDOL softgel cps. 10 x 400 mg','RAPIDOL softgel cps. 20 x 200 mg','RAPTEN-K DRG.10X50MG.','RECEPT PR.PERUT INT. I BALANS sampon 400 ml','RECEPT SAMPON ZA ZAJAKNUVANJE-ENERGETIK','RECTOSTOP original mast 50ml','RECUGEL GEL za ochi 10gr','REDRINGS Noktarica golema RED126','REDUPETIN krem 20ml','REGINA DIV KOSTEN I CRVEN LOZOV LIST krema 250 ml','RELAX 30 ML za mazi','RELAX 30 ML za zeni','RESEPT GEL ZA DEZINFEKCIJA 500ml','RESEPT SPRAY 80ml','RESEPT ZA DEZINFEKCIJA 500ml','REVALID ANTI AGING FLUID 100ml','REVALID ANTI AGING SHAMPOO 200ml','REVALID NUTRI REPAIR MASK 150ML','Revalid regeneratot 250 ml','REVALID SERUM protiv opaganje 50ml','REVALID SHAMPON protiv opaganje 200ml','REVUAR - katalog za lakovi plastichen','REVUAR - polica golema','REVUAR - polica za karmini','REVUAR - polica/plastichna za karmin SOFT/MAT','REVUAR - tester za techen karmin LONG LASTING','REVUAR - tester za techen karmin SOFT/MAT','REVUAR lak za nokti 50 sec','REVUAR moliv vodootporen','REVUAR techen karmin LONG LASTING','REVUAR techen karmin SOFT MAT','RHINOSTOP sirup 100 ml (101 mg + 1,01 mg + 20,20 mg)','RHINOSTOP tbl. 10 x(25,1 mg+2,54 mg +61,20 mg)','RHODIOLA cps. 500mg/60','RICINUSOVO maslo 50 ml','RINASEK tbl. 10 x (60 mg + 2,5 mg)','ROMED- DIGITALEN TOPLOMER','ROSAL MLEKO-MED lip balsam','ROSAL NATURAL lip balsam','ROSAL SENSITIVE lip balsam','ROSAL SHINE lip balsam','ROWATINEX cps. x 50','RUPURUT tbl. 20 x 500 mg','EUC.63944 SUN ALERGY SPF 50+ krem-gel 150ml','RUSKA VODA sprej 100ml.','EUC.SUN SPF30 OIL CONTROL DRY TOUCH 200ML','SANOSTOL +FE (zelezo) 230ml.','EUC.SUN SPF50+ SENSITIVE PROTECT','SATTWA KOLAGEN dnevna krema 55 ml','EUC.69613 STRONG PERSP. DEO ROLL-ON 50ml','SATTWA VITAMIN C krema 55 ml','EUC.83524 HYALURON FILLER SERUM 30ml','SCHOLL VELVET SMOOTH aparat peti ROZEV','SEBAMED BABY balsam za usni 4.7g','EUC.63536 hialuron filer okolu oci 15ml','SELITOP TBL.X40','SENSILAB HOLESTOP cps x 60','EUC.83505 ANTI-PIGMENT DN.KR.SPF30 50ml','SENSIVIT sol 10ml','SENSODYNE FLUOR pasta za zabi 75 ml','SENSODYNE konec za zabi','SENTIS CAPS. X 30','INN- IMUNITINN MR X10','SEPTANAZAL SPAY ZA DECA','SEPTANAZAL SPAY ZA VOZRASNI','SEPTOLETE MENTOL pastili x 30','VICHY Aminexil ампули против опаѓање на косата за мажи X21','SEPTOLETE total LIMON/BOZEL x 16','SEPTOLETE TOTAL pastili za grlo x 16','SEPTOLETE TOTAL SPREY ZA GRLO','SERRAPEPTASE 80 000IU cpsx30 VITON','SET LIP BAUME 200ml+LIP CLEAN OIL 200ml+GRATIS EAU 50ml','SHARENI MASKI ZA VOZRASNI L','LA ROCHE HYDRAPHASE RICH HA','VICHY сет Slow Age дневна+ ноќна крема за лице','SIDERAL GOCCE sol. 30ml','WELEDA- SMIRUVACKA KUPKA ZA DECA OD NEVEN 200ML','VICHY Dermablend 3D корективна пудра за масна кожа и кожа склона кон акни, № 15','VICHY Dermablend 3D корективна пудра за масна кожа и кожа склона кон акни, № 20','VICHY Dermablend 3D корективна пудра за масна кожа и кожа склона кон акни, № 35','VICHY сет Liftactive Suprime дневна+ ноќна крема за лице','SILBEN NANO SPAY 125ml.','SILK vosok vo alum.sad 100 gr.','SILVERTUSS spray za NOS 15ml','SILYMARIN cps. 30 x 100 mg','SINOMARIN ALGAE plus 30ml','SINOMARIN MINI SPREY 30ML','SINOMARIN MONODOSE 18 x 5ml','SINOMARIN sprej za deca 100 ml','SINOMARIN za vozrasni 125 ml','SIRUP OD ISLANDSKI LISAJ','SISTEM za infuzija - HITECARE','SLIM FIT CAJ filter x 20','SMECTA kesicki 10 x 3g','SMOKERS(PROP+ACD) sirup 150 ml','SNIZSTOP tbl. x 30','SODA BICARBONA medicinska 1kr','SODA BIKARBONA 500mg','SODA BIKARBONA FREE GLUTEN 200G','SODA BIKARBONA TBL X 10 CELASA','SODA BIKARBONA TBL. X 20 CELASA','SOFT TOUCH ANTIBAKT. GEL 50ml','SOLDEVIT D3 sprej 10 ml','SPATULI DRVENI x100','SPIRANTO FLASTER 5x 5sm/5 vo pakuvanje -4U PHARMA','SPIRULINA NIGRITA tbl.120','SPIRULINA tbl. 300 SAN SEBASTIJAN','SPIRULINA tbl.600 SAN SEBASTIJAN','SPRAY 8 ZA BRZO ZARASNUVANJE RANI','SPRIC 5ML X 100 ROMED','SPRIC trodelen 10 ML x 100','SPRIC trodelen 3 ML x 100','SPRIC trodelen 5ML X 100','URI.CU-ZN gel za mienje 200 ml','SREBRENA VODA 200ML','STAPCE ZA BRIS-STERILNO (ASTR)','STEVIA ZERO CAL tbl. x 100','STOMACHON caps.x30','STOMATIDIN r-r 200 ml (1 mg/ml)','STOP GRC x 50 tbl.','STREPFEN PASTILIX16 MED I LIMUN','STREPSILS LIMON bez seker x 16','BIODERMA PIGMENTBIO C CONCETRATE 15ml','STREPSILS MENTHOL/EUKALIPTUS oribleti x 24','BIODERMA PIGMENTBIO DAILY CARE SPF50+ 40ml','SUDOCREM krem 60g','SUDOCREM zashtiten krem za bebe 125g','BIODERMA PIGMENTBIO FOAMING CREAM 200 ml','SVEDSKA GORCILKA 250 ml.','SYNERGIY VIT.D3 2000iu cps x30','BIODERMA PIGMENTBIO NIGHT RENEWER 50ml','SYNERGY BETA CAROTENE x 60cps','BIODERMA PIGMENTBIO SENSITIV 75ml','SYNERGY FERTILIMIN 60 caps.','SYNERGY MG CITRAT + B6(350+6MG)X60CPS','SYNERGY OMEGA 3 X 60 CAPS','SYNERGY SELENIUM 100mg x 60tbl','SYNERGY vit. B12 100mcg X 60subl.tbl','SYNERGY VIT. C 1000MG X 60CAPS','SYNERGY VIT. C 500mg X 60CAPS','SYNERGY VIT. E CAPS.60X400IE','SYNERGY VITAMIN B6 tbl.60 x 50 mg','SYNERGY VOLURINE x 30cps','SYNERGY ZINC 60x15mg.','SYSTANE BALANCE sol. 10 ml','SYSTANE sol. 10 ml','SYSTANE ULTRA sol. 10 ml','TAMPAX tamponi/regular/16','TAMPAX tamponi/super/16','TAMPONI O.B normal/16','TAMPONI O.B normal/8','TAMPONI O.B PROCOMFORT super PLUS/16','TEARS NATURALE sol. 15 ml','TECNA pudra 100 ml','TECNA PUDRA SO ANESTEZIN 100 ml','TEMA CALCIUM 400 mg X 2eff.0','BIODERMA SEBIUM musant gel 200ML.','TERMOFOR 3L','WELEDA-LOSION ZA BEBINJA OD NEVEN','TERMOMETAR LASERSKI QUIKO ERA','BIODERMA SENSIBIO micel. r-or 100 ml','TERMOMETAR ZA FRIDZIDER - DIGITALEN','SYN-OSTEOFIT FORTE CAPS X60','TEST ZA BREMENOST SELF CLEAR','SYN-SYNFOLINE CAPS X60','TEST ZA OVULACIJA OVIEW','SYNERGY OMEGA 3-6-9 gel cps. x 60','THERESIENOL MASLO 10 X 1 ML','THERESIENOL MASLO 5ml','THERMOMETAR bezkontakten JZK-601','THIOMUCASE anticelul.gel','TIFOL film obl.tbl. 30 x 0,4 mg','TIGEX 320905 KUTIJA ZA CUCLA 0+m','TIGEX 730100 LAZALKA X 2 SILIKON 0-6M ZEBRA','TONIMER balz.soft nose gel 15ml','TONIMER LAB PANTEXYL SPRAY 100ML','TOOTHPOP lizavche - JAGODA','TOOTHPOP lizavche - MALINA','TOOTHPOP lizavche - MULTIVITAMINI','TOTHEMA (Fe+Mg+Cu) amp. 10ml x 20','TRACHISAN oribl.20x(0,5mg+1mg+1mg)','TRANQUIL cps.x 30','TROSLOJNI MASKI za ednokratna upotreba','TYLOL HOT kesicki x 12','TYLOL HOT PEDIATRIC kesicki x 12','UNITEARS SOL 10ML- UNIMED','UR- HYSEAC SOS PASTE 15G','URIAGE AGE PROTECT KREM LICE 40ml MULTIACTION','4U BIMUNAL IMUNO ADULTS CAPSX30','4U VIRANTO FORTE ADULTS CPSX20','URIAGE XEMOSE BABY MASLO PROTIV CESHANJE 500ml','URIAGE BABY MASLO ZA KAPENJE 500ml','ALVOGEN ORS JAGODA','URIAGE BEBE 1ER ZASTITNA KREMA 100ml.','APURETIN SLIM caps.x 60','BECUTAN KIDS VIT.B-COMPLEX sirup 100ml','URIAGE HYSEAC MASKA PEEL-OFF 50ml','URIAGE ROSELIAN CC KREM SPF30 40 ml','URIAGE ROSELIAN KREM PF30 40ml','URIAGE shampon protiv PRVUT 200ML','URIAGE TERM.MICELARNA VODA PLAVA 250ml','URIAGE TERM.MICELARNA VODA ROZE 250ml','URIAGE TERM.MICELARNA VODA ZELENA 250ml','CARBO MEDICINALIS  CARBOMED   tbl. 30 x 150 mg','URIAGE XEMOSE MASLEN balsam 500ml.','URIFAR pulv. x 14 kesicki','DR.THEISS BRSHLEN sir. 250ML','URIMIL GEL 50ML','URIN KESI detski -UNISEX -zolto/zeleni','URIN KESI unisex- PEDIJATRISKI','DR.VITON  K2 KOMPLEX X30 caps.','URO 3 caps.x20','VAGISAN vaginaleti x 7','VALERIAL sol. 30 ml (*ALK)','DR.WOLZ DARMFLORA PLUS CAPS X 10','VATA sanitetska CIK-CAK 50g','VAZELIN 100 gr','VAZELIN NEVEN i d-panthenol 50 ml','VAZELIN NEVEN/D-PANTENOL 100ml','VEET krem za dep.cveten-rozev 100ml','VEET krema za depil.so aloe vera-plav 12024-04-22T20:02:07.945501986Z 00ml','VEET LADEN VOSOK NATURAL / 20 LENTI','VEET LADEN VOSOK TRAKI SENS.X40','VEET lenti za depilacija x 20','VEET LENTI ZA DEPILACIJA x40','VEET TRAKI ZA LICE MALI x 20PCS','Veet traki za telo plavi/ 20','VENASALIK KREM GEL ZA NOZE 50ml','VENDOKSIN kapki 50 ml','VICHY Aqualia Thermal крема за нормална до комбинирана кожа 50ML','VICHY Aqualia Thermal крема за сува кожа 50ML','VICHY Idealia крема за нормална до комбинирана кожа 50ml','VIDERMINA CLX ovuli 10X3gr','VIDERMINA PREBIOTIC ovuli x 10','VIRFIX br. 1 - 2m','VIRFIX br. 3 - 2m','VIRFIX br. 4 - 2m','VIRFIX br. 5 - 2m','VIRFIX br. 6 - 2m','VITA krem so kolagen 50ml','VITABIOTICS FEROGLOBULIN B12 cps. x30','VITABIOTICS JOINTACE colagen tbl.x 30','VITABIOTICS OSTEOCARE tbl x 30','ESI NOGLIC tbl. x 30','ESI NO DOL TRAUMGEL gel 50 ml','VITAMIN AD sol.10 ml (22522 IU+5000 IU)/ml','VITAMIN B17 caps.x 60','ESPUMISAN cps. 25 x 40 mg','ESPUMISAN cps. 50 x 40 mg','ESPUMISAN L per.emul.30 ml (40 mg/ml)','FEMISAN A sol 30ml.','VITAMIN C caps.30 x 500mg Geoprom','FERVEX children sugar freeX8','VITAMIN C tbl. 250 x 500 mg','FITALP tonik 150 ml','VITAMIN D3 2000 IE SUNDOVIT X60 caps','VITAMIN D3 2000 PROTEGO','VITAMIN D3 4000 IE X 60 caps.','VITROGEN X16AMP.','VIVAAQUA flas.vodoot. steril 10x9','VIVAAQUA FLASTER VODOOTPOREN ( 10X9 ) X 50','VIVAFLEX (tkaen) el.zavoj 8cm x 5m','VIVAPORE FLASTER ( 5X7 ) X100','VIVAPORE ster.flaster 10x9cm','H.A COLLAGEN COMPLEX TBL. X 60','VIVAPORE ster.flaster 5x7cm','H.A DAY-VIT PROBIO tbl.x30','H.A DIGESTON MAX TBL.30','HEALTH AID JUNIOR VIT tbl.x 30','Vizol S Allegy sol. 10 ml','HA CURCUMIN 3 tbl.x30','HA WINTERVITS TBL X 30','HA-ALPHA LIPOIC ACID CPS.60X250MG','HA-GASTONE CAPS X 60','VULA test za bremenost','HA-SERRAPEPTASE TBL 30 X 250 000 IE','HA-TURMERIC ROOT EXT. TBL.X60','HA-VITAMIN C tbl. 30 x 1500 MG','HA-VITAMIN D3 caps. 30 x 5000 IU','ZASLADUVAC GALILEO 1200 tbl','ZASTITNA MASKA FFP1','ZAVOJ KALIKO 10x5 cm','HEPAFAR FORTE CAPS.X30','ZAVOJ KALIKO 5X5','ZAVOJ KALIKO 6X5','HUMANA COLIMIL PLUS KAPKI 30ml','HYLO-DUAL sol.10ml','ZDRAVE sampon CRN BIBER 200ml','ZDRAVE sampon crn biber 390ml','ZDRAVE SAMPON FORTE PROTIV PERUT 150ML.','IMMUNOBALANS cps. x60','ZDRAVE sampon JAGLEN za detoksikacija 200ml','ZELEN CAJ SO GUMBIR FILTERX20','ZELENA GLINA - vnatreshna upotreba 200 gr','ZELENA GLINA- nadvoreshna upotreba 500 gr','ZEWA PARFIMIRANI hart.mar./10','ISLA MEDIC PASTILI X20','K2+D3 WITAMINA caps.x30','CLA caps. 30 x 1000 mg','KUTIJA za lekovi nedelna','CURAPROX ENZYCAL ZERO pasta za zabi 75ml','CURAPROX ENZYCAL 1450 pasta za zabi 75ml','LEVIKER TBL.X30','CURAPROX PERIO PLUS BALANS rastvor 200ml','LUTEIN COMPLEX cps. x 30','CURAPROX PERIO PLUS SUPPORT pasta za zabi 75ml','CURAPROX PERIOPLUS FORTE rastvor 200ml','CURAPROX PERIOPLUS PROTECT rastvor 200ml','CURAPROX PERIOPLUS REGENERATE rastvor 200ml','NOW L- ARGININE CAPS. 100 X 500MG','NOW MACA caps.100X500 mg','NOW METHYL B-12 100 X 1000 mg','CURAPROX CPS 06 interdentalni cetki','NOW METHYL FOLAT 1000mcg x 90tbl','NOW NIACIN 25mg x 90cps','NOW OMEGA 3-6-9 cps.90 x 1200mg','NURSE HARVEYS sir. 145ml','ImmunoVita Kids 30 sachets','OSTEOVITAL  FORTE SUM.TBL. 20X1000MG','PICO C gtt 12ml','PLUSMED APARAT ZA GLIKEMIJA','Zoono Hand Sanitizer 500ml','PROSTAMOL UNO cps.x 30','PROSTATOL COMPLEX X30','UR 075 BABY HIDRATATION MLEKO 500ML','SILIMARIN FORTE CAPS. 30 X 200MG','SILYMARIN DUO tbl. x 30','UR HYSEAC EXFOLIENTING MASK','UR HYSEAC NEW SKIN SERUM 40ML','UR HYSEAC PURIFYING OIL maslo za mienje 100ml','UR HYSEAC TONIK ZA LICE 250ML','URI. D.S. emulzija 40 ml','SOPHIE-616624 ZIRAFA + SO PURE GLODALKA','SOPHIE - 523510 SET ZA HIGIENA','SOPHIE - 523518 SET ZA BANJANJE','SOPHIE-200318 SO PURE GLODALKA SOFT','SOPHIE-200319 SO PURE GLODALKA VERY SOFT','SOPHIE - 450408 MEKI SILIKONSKI LAZICKI X 2','UR XEMOSE MASLO ZA KAPENJE 200ML','Cicaplast Baume B5 SPF 50- За обновување и регенерација на површинскиот слој на кожата.Со заштитен фактор 50+','Cicaplast Baume B5- За обновување и регенерација на површинскиот слој на кожата','La Roche-Posay термална вода','EFFACLAR DUO+ EFF GEL 400ML - SET','EFFACLAR Мицеларна вода - масна и чувствителна кожа','Effaclar H крема за миење лице','NOW COENZIM Q10 cps.60 x 30mg','Effaclar Micro-Peeling гел за лице и тело- Гел за чистење на кожа склона кон неправилности','NOW D-MANOSE cps.120 x 500mg','VB-PREGNACARE BEFORE CONCEPTION TBL.X30','LIPIKAR BAUME M 400ML + LIPIKAR SYNDET 400ML','Lipikar маслена купка-Масло за чистење на кожа сколона кон атописки дерматит','Lipikar Gel Lavant-Смирувачки гел за туширање','Lipikar Syndet AP+ -Кремаст гел за миење, за сува и иритирана кожа подложна кон атопија','Lipikar Xerand- Крема за обнова на кожата на рацете','Effaclar гел за чистење лице-за масна и чувствителна кожа','Effaclar Ultra Концентриран серум- Концентрирн серум против флеки и неправилности на кожата','Hyalu B5 серум-Серум против брчки и еластичност за чувствителна кожа','Serozinc РАСТВОР НА ЦИНК СУЛФАТ','VIRANTO FORTE','VISET 0.5MG/ML KAPKI ZA OKO 10ML','Vizol S intensive sol. 10 ml','W-IMMUN SELECT CPSX60','VICHY SLOW AGE NIGHT 50ML','VICHY Idealia крема за сува кожа 50 ml','VICHY Liftactive Collagen крема за дневна нега за сите типови на кожа 50ml','VICHY Liftactive Supreme дневна крема за нормална до комбинирана кожа 50ml','VICHY MINERALBLEND 06 30ML','VICHY MINERALBLEND 09 30ML','VICHY Liftactive Collagen крема за дневна нега за сите типови на кожа со заштитен фактор 25 50ml','VICHY Normaderm SOS сулфурна паста за акни 20ML','SEBAMED BABY krem ekstra mek 50 ml','SEBAMED BABY krem protiv osip 100 ml','SEBAMED BABY krem za lice 50 ml','SEBAMED BABY losion 200 ml','SEBAMED BABY sampon 150 ml','TOPLOMER HUMAN-ZIVIN x 1 TOPLOMER HUMAN-ZIVIN x 1','SEBAMED CF gel protiv akni 10 ml','SEBAMED CF tonirana krema za akni 10 ml','SEBAMED CF pena za lice 150 ml','SEBAMED CF sapun 100gr.','SEBAMED CF tonik za lice 150 ml','SEBAMED shampon perut 200 ml','Подхранувачки супер калциум во прав-10','Супер калциум за деца во прав-10','Супер калциум со лецитин-20 капсули','Кордицепс-100 капсули','Хитосан-100 капсули','Спирулина-100 капсули','Приспивни дуо-60 таблети','Масло од лук-60 капсули','Мултифункционален уред-биоенергија','Мултифункционален уред-фрижидер','Здрава перница','Здрава прекривка','Здрав душек','Антилипиден чај-40 кесички','Цинк-60 капсули','Дигест-90 таблети','Женски хигиенски влошки','SYNERGY FERROFECT x30 tbl','SYNERGY VIT.D3 2000iu cps x30','SYNERGY VITAMIN K 80mg','JAM-MG 90x250mg','JAM-ZN 100x10mg','H. AID HAIR-VIT cps.x 30','H-AID METHYLCOBALAMIN B12 tbl. x 60','H-AID PROSTAVITAL cps. x 30','H-AID VITAMIN B99 COMPLEX tbl. x60','H-AID LIVERCARE tbl. X 60','H-AID MAGCITRA tbl. X 60','H-AID OSTEOVIT tbl. x 60','H-AID RED YEAST rice tbl. x 90','H-AID TEA TREE OIL sapun 100g','H-AID VITAMIN D3 1000 i.u spray','H-AID VITAMIN E maslo 100% 50ml','DOC VITAMIN D3 1000IE TBL.X60','H-AID WHEAT GERM OIL cps. x 60','NU-ASHWAGANDHA caps. 90 x 450mg','NU-MAGNEZIUM CITRAT caps. X 90','NU-NAC 600mg','NU-SELENIUM tbl. 100 x 100mcg','NU-SERRAZIMES caps. x 90','NU-VITAMIN D3 1000 IE x 180 soft caps.','NU-VITAMIN K2 100 mcg','NU-VIT.D3 10.000 IU','NU-CHOLINE & INOSITOL caps. x 100','NU-COQ10 caps. 50 x 100mg','NU-INULIN PRASHOK 227gr.','Anthelios XL Dry Touch Anti-Shine- Крема со заштитен фактор 50+ против масен сјај на лицето','Anthelios SHAKA FLUID','ANTHELIOS SUN INTOLERANCE Крема за лице со Невросензин за дневна превенција на реакции на кожата предизвикани од сонцето','ANTI PIGM.BB CR 50+','Cicaplast Gel B5- За обновување и регенерација на површинскиот слој на кожата.','Effaclar тоник-Астрингентен тоник','Effaclar Duo (+) SPF30-Нега на кожа склона кон неправилности и акни со заштитен фактор 30+','EFFACLAR duo(+) UNIFIANT LIGHT','Effaclar Duo (+)-Нега на кожа склона кон неправилности и акни','Effaclar Mat-Хидратантна нега за масна кожа','Hyalu B5 крема за пределот околу очите- Крема против брчки за подрачјето околу очите','Hydraphase Intense Riche-Интезивна рехидратантна нега за сува и чувствителна кожа','Hydreane Legere -Хидратантна нега за нормална до комбинирана кожа','Hydreane Riche -Хидратантна нега за сува и чувствителна кожа','LIPIKAR LAIT UREA 5+- Млеко за исклучително сува и груба кожа','PURE VIT C10 SERUM -Антиоксидативен обновувачки серум против брчки','PHYSIO MICELLAR WATER ULTRA 400ML','Rosaliac AR Intense-За чувствителна кожа склона кон купероза','TOLERIANE SENSITIV LE TEINT CREME MEDIUM 50ml-180700','TOLERIANE SENSITIVE CREME 40ml','VICHY Aminexil ампули против опаѓање на косата за жени X21','VICHY Capital Soleil крема со заштитен фактор 50, против стареење 50ml','VICHY Capital Soleil тонирана крема со заштитен фактор 50, против темни флеки 50ml','ND PHYTOSOL KR.50ML+ GRATIS ND GEL','VICHY спреј со термална вода 150ml','Vichy Capital Soleil Dry touch fluid ББ крема со заштитен фактор 50 за комбинирана до масна кожа 50ml','VICHY Dermablend корективна пудра за сите типови на кожа № 15','VICHY Liftactive крема за околу очи 15ml','VICHY MINERAL BLEND 03 30ml','VICHY Pureté Thermale 3 во 1 200ml','VICHY Pureté Thermale пена за чистење на чувствителна кожа на лицето 150ml','VICHY Mineral Micellar Milk for dry skin 400ml','VICHY Slow Age крема за очи за првите знаци на стареење 15ml','VICHY Slow Age Fluid за првите знаци на стареење 50ml','UR-XEMOSE BABY BALSAM PROTIV CESANJE 200ml','URI.CU-ZN BEBE sprej 100ml','BD FOTODERM KID SPF50 + SPRAY','BD SENSIBIO EYE GEL 15ml','BIODERMA ATODERM KREM 500ML','BIODERMA CICABIO KREM SPF50+ 30ml','BIODERMA SENSIBIO DS+ krem 40ml','BIODERMA SENSIBIO GEL MOUSSANT 100ml','ANTH AGE DAILY CREAM SPF50+','ANTH GEL CREAM COLOR SPF50+','ANTHELIOS ANTI-IMPERFECTIONS SPF50+ -Крема со заштитен фактор 50+ за кожа склона кон неправилности','ANTH KA+ SPF50+','ANTH LOTION SPF30+ ECOTUB 250ML','ANTH LOTION SPF50+ ECOTUBE 250ML','URI. BARIESUN SPF 30 KREM 50ML','URI. BARIESUN SPF 50 PUDRA SVETLA','URI BARIESUN SPF 30 SPREJ 200ML','URI. BARIESUN SPF 50 PUDRA TEMNA','URIAGE TERMALNA VODA duo set 300ml.','URIAGE ROLL-ON 3 ACTIVE X 2','URI. TERMALNA MICELARNA VODA ROZEVA 500ML X 2','URI. PROMO STIK HIDRA ZA USNI X 2','URI. EAU TERM. KREMA ZA RACE 50ML X 2','URI. BARIEDERM CICA SERUM 30ML','URI. BARIEDERM CICA GEL-KREM 40ML','URI. EAU THERM.ESSENCE 100ML','VICHY Dercos Energizing шампон за зајакнување и против опаѓање на косата 200ml','VICHY Dercos ultra soothing Normal to Dry Hair','VICHY Dercos Oil Control Shampoo','BD FOTODERM NUDE TOUCH SPF50+ 40ml','BD FOTODERM AQUA FLUID SPF50+ 40ml','BD FOTODERM SPOT AGE SPEF50+krem 40ml','BD FOTODERM AKN MAT FLUID SPF30','BD PHOTODERM MAX KR.SPF50+','SENSIBIO AR BB-BIODERMA','BIODERMA SENSIBIO LIGHT krem 40ml','Anthelios ULTRA SPF 50+ Водоотпорна крема за лице со заштитен фактор 50+','TOLERIANE НЕГУВАЧКИ ГЕЛ ЗА МИЕЊЕ НА ЛИЦЕ','VICHY Beo Bille Large ролон сет 1+1 100ML','DEO MINERAL ROLON 1+1 SET','VICHY Capital Soleil Mattifying 3-in-1 SPF 50 50ML','VICHY Capital Soleil Fresh Protective млеко за возрасни со заштитен фактор 50+ 300ml','VICHY Capital Soleil Gentle Protective млеко за деца со заштитен фактор 50+ 300 ml','VICHY Liftactiv Specialist Peptide-C ампули за тенки линии и брчки x 10','PHOTODERM COVER TOUCH 50+','RILASTIL D-CLAR DEPIGM. DROPS','WELEDA skin food krem 75ml','RILASTIL D-CLAR MICROPEELING','WELEDA maslo od neven (bez mirisi)','RILASTIL D-CLAR SPF 50','WELEDA krem za lice za deca od neven','WELEDA krem od neven pel. reg.','RILASTIL D-CLEAR DAYILY DEPIGM. CREAM','DR.HAUSCHKA melisa dneven krem 30ml','RILASTIL EAP LIPOGEL','DR.HAUSCHKA Mleko za cistenje 145ml','RILASTIL krem protiv strii 200ml','RILASTIL XEROLACT 12% 400ML','BIODERMA ATODERM huile de douche 200ml','RILASTIL XEROLACT 18% 100ML','BIODERMA SENSIBIO RICH krem 40ml','RILASTIL XEROLACT 30%','WELEDA Bel Slez losion 200ml','RILASTIL XEROLACT PODOS LIPOGEL 100ML','TOLERIANE SENSITIVE RICHE-Пребиотичка хидратантна нега која ја намалува чувствителноста на кожата.','VICHY Densi-Solutions концентриран лосион за тенка и ретка коса 100ML','TETE KUPKA PENLIVA ZIMSKA NEZNOST 420ML','TETESEPT DOZA BLAGODARNOST','TETESEPT GEL KREAM HELLO BEAUTY','TETESEPT HELLO HAPPINESS','TETESEPT HELLO WINTERCARE','TETESEPT KUPKA BACK WARM BATH','TETESEPT KUPKA DEEP RELAX','EUC.69617 UREA 10%complete repair lotion','TETESEPT KUPKA JOINT&amp;MUSCLE','JAM-VIT.C 500mg+D3 500IE TBL.X75','TETESEPT KUPKA MALA SIRENA','INN-DIART SPRIC 1,8% 2ML','TETESEPT KUPKA MUSCLE RELAX','INN-FORTINN KESI X 30','TETESEPT KUPKA PENLIVA IGRA NA DOZD','TETESEPT KUPKA PENLIVA ZIMSKA MAGIJA 420ML','INN-TENDOCILINN KESI X 28','TETESEPT MAL ASTRONAUT','ESI LE DIECI ERBE COLON CLEANSE tbl.x60','TETESEPT POTRAGA PO BOGATSTVO','TETESEPT SET KUPKI','TETESEPT SOL ZA KAPENJE ANTISTRES','TETESEPT SOL ZA KAPENJE BACK&amp;SHOULDER 600G','4U BIMUNAL SIR.300ML','TETESEPT SOL ZA KAPENJE DEEP RELAXATION 600G','TETESEPT SOL ZA KAPENJE JOINTS&amp;MUSCLES 600G','TETESEPT SOL ZA KAPENJE MALKU SREKJA','TETESEPT SOL ZA KAPENJE PARCE LJUBOV','TETESEPT TAJNATA NA KLEOPATRA','TETESEPT VREME ZA ODMOR','TETESEPT VULKANSKI SVET','ANTHELIOS dermo-pediatrics lotion за мокра или сува детска кожа. Многу висока заштита.','ANTH DERMO KIDS LOTION 100ML','DR. HAUSCHKA Tonik za lice 100ml','DR. HAUSCHKA krem za cistenje 50ml','DR. HAUSCHKA Krem od rozi Light 30ml','DR. HAUSCHKA Dnev.revit.krem-oci','ATODERM GEL 1L','ATODERM INTESIVE EYE','BD FOTODERM MINERAL SPF50+','VICHY Neovadiol Phytosculpt за нега на врат и контури на лицето 50ml','VICHY Neovadiol Contours крем за очи и усни 15ml','WELEDA citrus roll on 50ml.','WELEDA sensitive mleko kids SPF-30-150ml','WELEDA sensitiv kids krem SPF-50-50ml','WELEDA DETSKI SHAMPON + KUPKA PORTOKAL 200ml','WELEDA shampon i gel za tus. LIMON 200ml','WELEDA SKIN FOOD BODY 150ml','WELEDA maslo za masaza na trudnici-strii 100ml','WELEDA piling za telo od breza 150ml','WELEDA maslo od breza prot.celulit 100ml','ANTHELIOS XL wet gel за мокра или сува кожа со многу висо2024-04-22T20:02:07.945501986Z ка заштита','ANTH. WET GEL KIDS 250ML','VICHY cis dry touch fluid 50spf 50ml','VICHY Capital Soleil Fresh Protective млеко за деца и возрасни со заштитен фактор30+ 300ml','VICHY Capital Soleil балсам за смирување на црвенило предизвикано од сончање 100ml','VICHY Ideal Soleil Solar Protective Water Spf 50 200 ml','VICHY Capital Soleil Solar-Protective Water со хујалуронска киселина и заштитен фактор 30 200ml','ABSOLUTE DRY DAB-ON 35ML','OLIOVITA BALZAM 10ml','SET SENSITIV MICELARNA+LIPIKAR 400ML','SET MIC.WATER+LIPIKAR GEL 400ML','BDFOTODERM MAX SPRAY SPF50+ 400ml','BD FOTODERM M SPF 50+ 40 ml','BD FOTODERM SPRAY SPF30+ 400 ml','BD PHOTODERM BRONZE SPF50+','BD PHOTODERM MAX TONIR.KR.SPF50+','BD PHOTODERM MAX ULTRA FLUID 50+','BD PHOTODERM SENS.SPF50+ 100 ml','EMBRYOLISSE OSVEZUVACKI CVETEN TONIK','DR. HAUSCHKA BALANSIRACKI DNEVEN LOSION','EMBRYOLISSE CREME FLUID 500ML','EMBRYOLISSE FILADERME EMULZIJA','EMBRYOLISSE CICALISSE CREAM','EMBRYOLISSE KREM PROTIV BRCKI','EMBRYOLISSE ANTI AGE FIRMING CREAM','EMBRYOLISSE SMOOTHING EYE CONTOUR CARE','EMBRYOLISSE BB CREAM SPF20','EMBRYOLISSE CC CREAM','VICHY Liftactive Flexiteint № 15 30 ml','VICHY Liftactive Flexiteint № 25 30 ml','VICHY Liftactive Flexiteint № 35 30 ml','ROSE VALLIS ANTI AGE NOKJNA KREMA','ROSA VALLIS MICELARNA VODA 250ML','ROSA VALISS ANTI AGE DNEVNA KREMA','INN-D-MANOZIN KESIX10','INN-D-MANOZINN PROTECT KESIX10','INN-GRAMINN CAPS.X30','INN-GRAMINN SUPP.X10','INN-LONGUPINN SPRAY 50ml','INN-LUPRINN CAPS.X30','INN-MIOCYSTINN FERTILE KESIX20','INN-NATTOKINN CAPS.X30','INN-R-LIPOINN CAPS.30X150mg','INN-SERAPINN CAPS.30X60000IE','INN-SPERGININN Q10 TBL.X16','BABE- STOP AKN PURIFYING CLEANSING GEL 200ML','BABE- STOP AKN MATTIFYING MOISTURISER 50ML','BABE- STOP AKN KERATOLYTIC FLUID 30ML','BABE- PEDIATRIC SUNSCREEN WET SKIN SPF50 200ML','BABE- PEDIATRIC EXTRA MILD SHAMPOO 200ML','BABE- PEDIATRIC CRADLE CAP SHAMPOO 200ML','BABE- PEDIATRIC ATOPIC SKIN OIL SOAP 200ML','BABE- PEDIATRIC ATOPIC SKIN EMOLLIENT CREAM 200ML','BABE- HA+ MULTI REJUVENATING BOOSTER 50ML','BABE- HA+ MULTI PROTECTOR CREAM SPF30 50ML','BABE- HA+ EYES AND LIPS TENSOR MULTI CORRECTOR 15ML','BABE- FACE SUNSCREEN SUPER FLUID SPF50 50ML','BABE- FACE ESS SOOTHING MICELLAR GEL 245ML','BABE- FACE ESS HYDRONOURSHING CREAM SPF20 50ML','BABE- FACE ESS HYDRO 24H REACTIVE SKIN 50ML','BABE- BODY OIL SOAP 500ML','BABE- BODY ALOE VERA 300ML','BABE- BODY 10% UREA REPAIRING LOTION 500ML','URIAGE BARIESUN CREM SPF50+','UR-189-BARIESUN 100 SPF50+','VICHY Mineral 89 Probiotic Fractions серум за регенрација на кожата 30ml','VICHY Mineral 89 Daily Booster 50ML','VICHY Mineral 89 Eyes за околу очи 15ml','REVALID ANTI DANDRUFF SHAMPOO 250ML','Revalid shampon 250 ml','REVALID TONIK amp.20x6ml','BIODERMA PIGMENTBIO 250ml','BIODERMA SEBIUM mic.voda 100ml','LIPIKAR LAIT LOTION 400ML','NODE K 150ML','EUC.63944 SUN ALERGY SPF 50+ krem-gel 150ml','SIXTH SENSE HIJALURONSKI SERUM BEAUTY BOOSTER','EUC.SUN SPF50+ SENSITIVE PROTECT','SIXTH SENSE KREMA PROTIV STAREENJE 40ML','EUC.83524 HYALURON FILLER SERUM 30ml','SIXTH SENSE KREMA ZA KOMBINIRANA KOZA 40ML','EUC.83505 ANTI-PIGMENT DN.KR.SPF30 50ml','INN- IMUNITINN MR X10','SIXTH SENSE KREMA ZA MASNA KOZA','LA ROCHE HYDRAPHASE Light','SIXTH SENSE KREMA ZA SUVA I NORMALNA KOZA 40ML','WELEDA maslo za masaza na gradi pri laktacija 50ml','SIXTH SENSE KREM ZA IZBELUVANJE','SIXTH SENSE MASLO ZA KUTIKULI','VICHY Dermablend 3D корективна пудра за масна кожа и кожа склона кон акни, № 35','SIXTH SENSE MICELARNA VODA 250ml','VICHY Liftactive Collagen Specialist ноќна крема за сите типови кожа','SIXTH SENSE PURE ORGANIK ELIKSIR','SIXTH SENSE SERUM ZA DLABINSKA HIDRATACIJA','CICAPLAST B5 SPREY','EFFACLAR DUO SET EFF. GEL+ SEROZINC+ EFF.DUO CR','SEBIUM SET GLOBAL/SEBIUM GEL MOUSSANT-penest gel','AKC UR-214-XEMOSE +MASLO 200ML','SYN-OSTEOFIT FORTE CAPS X60','SYN-SYNFOLINE CAPS X60','SYNERGY OMEGA 3-6-9 gel cps. x 60','VICHY Neovadiol Post-Menopause ноќна крема за сите типови кожа MB421200','4U VIRANTO FORTE ADULTS CPSX20','ALVOGEN ORS JAGODA','VICHY Neovadiol Post-Menopause дневна крема за сите типови кожа MB421400','BECUTAN KIDS VIT.B-COMPLEX sirup 100ml','CARBO MEDICINALIS  CARBOMED   tbl. 30 x 150 mg','VICHY Neovadiol Peri-Menopause ноќна крема за сите типови кожа MB421900','COLIPREV SOL.15ML','VICHY Neovadiol Peri-Menopause дневна крема за нормална до комбинирана кожа MB422300','DIET.BIOTIN tbl.x 30','VICHY Neovadiol Peri-Menopause дневна крема за сува кожа MB422700','D-MANURO granuli 10 x 1g','Dr.Hauschka hidratanten dneven losion 50ml','DR.LEO BABY D3 CAPS.30X400IE','DR.THEISS BRSHLEN sir. 250ML','DR.VITON  K2 KOMPLEX X30 caps.','DR.WOLZ DARMFLORA PLUS CAPS X 10','ESI NOGLIC tbl. x 30','ESI NO DOL TRAUMGEL gel 50 ml','ESPUMISAN cps. 25 x 40 mg','ESPUMISAN cps. 50 x 40 mg','ESPUMISAN L per.emul.30 ml (40 mg/ml)','FEMISAN A sol 30ml.','FERVEX children sugar freeX8','FITALP tonik 150 ml','FORVITA GLUKOZAMIN cps.30X500mg','FORVITA VIT.B12 tbl.60x100mcg.','FORVITA AVIREKS FORTE CPSX60','GARCIA SLIM X60TBL HEALTHAID','H.A COLLAGEN COMPLEX TBL. X 60','H.A DAY-VIT PROBIO tbl.x30','H.A DIGESTON MAX TBL.30','HEALTH AID JUNIOR VIT tbl.x 30','HA CURCUMIN 3 tbl.x30','HA WINTERVITS TBL X 30','HA-ALPHA LIPOIC ACID CPS.60X250MG','HA-GASTONE CAPS X 60','HA-SERRAPEPTASE TBL 30 X 250 000 IE','HA-TURMERIC ROOT EXT. TBL.X60','HA-VITAMIN C tbl. 30 x 1500 MG','HA-VITAMIN D3 caps. 30 x 5000 IU','HEPAFAR FORTE CAPS.X30','HUMANA COLIMIL PLUS KAPKI 30ml','HYLO-DUAL sol.10ml','IMMUNOBALANS cps. x60','IMUNOCINK ZA VOZRASNI  tbl.60 x 10mg','IMUNOCINK ZA DECA tbl.60 x 5mg','ISLA MEDIC PASTILI X20','K2+D3 WITAMINA caps.x30','CLA caps. 30 x 1000 mg','KUTIJA za lekovi nedelna','LEVIKER TBL.X30','LUTEIN COMPLEX cps. x 30','MULTILAC BABY SINBIOTIC KESIX10','NOW CALCIUM CITRAT tbl.x 100','NOW OMEGA-3 cps.100 x 1000mg','NOW  MAGNESIUM CITRAT tbl. 100X200mg','NOW ACIDOPHILUS 4X6 cps.X 60','NOW L- ARGININE CAPS. 100 X 500MG','NOW MACA caps.100X500 mg','NOW METHYL B-12 100 X 1000 mg','NOW METHYL FOLAT 1000mcg x 90tbl','NOW NIACIN 25mg x 90cps','NOW OMEGA 3-6-9 cps.90 x 1200mg','NURSE HARVEYS sir. 145ml','OSTEOVITAL  FORTE SUM.TBL. 20X1000MG','PICO C gtt 12ml','PLUSMED APARAT ZA GLIKEMIJA','PROSTAMOL UNO cps.x 30','PROSTATOL COMPLEX X30','SILIMARIN FORTE CAPS. 30 X 200MG','SILYMARIN DUO tbl. x 30','SOPHIE - 450409 NEKAPECKA CASA','SOPHIE - 460006 SET ZA JADENJE 6+','SOPHIE - 460008 MOJ PRV SET ZA JADENJE','SOPHIE-616624 ZIRAFA + SO PURE GLODALKA','SOPHIE - 523510 SET ZA HIGIENA','SOPHIE - 523518 SET ZA BANJANJE','SOPHIE-200318 SO PURE GLODALKA SOFT','SOPHIE-200319 SO PURE GLODALKA VERY SOFT','SOPHIE - 450408 MEKI SILIKONSKI LAZICKI X 2','TRAKI ZA SEKER MEDISIGN - 02 / 50','NOW COENZIM Q10 cps.60 x 30mg','NOW D-MANOSE cps.120 x 500mg','NOW UBIQUINOL COQH-CF CAPS.X60','TRIMEX SPIRULINA PACIF.tbl. x 100','TRIMEX SPIRULINA PACIF.tbl. X400','TRIMEX SPIRULINA PACIFICA prasok 141.75gr','TRIMEX SPIRULINA PACIF.tbl. X200','UTISEPT cps.x 30','VITABIOTICS VISIONACE ORIGINAL tbl.x 30','VB-PREGNACARE BEFORE CONCEPTION TBL.X30','VIRANTO FORTE','VISET 0.5MG/ML KAPKI ZA OKO 10ML','Vizol S intensive sol. 10 ml','WELEDA maslo za masaza na perineuim regijata 50ml','W-IMMUN SELECT CPSX60','VICHY 24h Tolerance Deo Sprey','VICHY 48h Deo Sprey- за сензитивна кожа','TOPLOMER HUMAN-ZIVIN x 1 TOPLOMER HUMAN-ZIVIN x 1','DOC BETA GLUCANS TBL.X60','DOC IRON ADVANCED CAPS.X60','DOC MSM/GLUCOSAMINE TBL.X60','DOC OMEGA 3 softgel X30','DOC MSM/VIT.C TBL.X60','DOC OMEGA 3-6-9 softgels X30','DOC ZINK/VIT.C TBL.X60','DOC VITAMIN D3 1000IE TBL.X60','URI.HYSEAC BL-stick 3 ml','WELEDA сет куферче- шампон за коса и тело, крем за пеленска регија и крем за лице','URI.HYSEAC DERMATOL.gel 150 ml','URIAGE HYSEAC FLUID SPF50+ 50ml','WELEDА масло за масажа на детско стомаче 50мл','RILASTIL ACNESTIL CLEANSING GEL 200ML','RILASTIL ACNESTIL CLEANSING MOUSSE 150ML','RILASTIL ACNESTIL KREM 50ML','RILASTIL ACNESTIL MAT CREAM 50ML','RILASTIL ATOPIC BALM 400ML','RILASTIL ATOPIC CLEАNSING OLI 250ML','RILASTIL D-CLAR DEPIGM. DROPS','RILASTIL D-CLAR MICROPEELING','RILASTIL D-CLAR SPF 50','RILASTIL D-CLEAR DAYILY DEPIGM. CREAM','RILASTIL EAP LIPOGEL','RILASTIL krem protiv strii 200ml','RILASTIL XEROLACT 12% 400ML','RILASTIL XEROLACT 18% 100ML','RILASTIL XEROLACT 30%','RILASTIL XEROLACT PODOS LIPOGEL 100ML','TOLERIANE DERMALLERGO LIGHT CREAM 40ml','TOLERIANE DERMALERGO EYE CREM 20ml','TOLERIANE DERMALLERGO CREAM 40ml','TOLERIANE DERMALLERGO FLUID 40ml','EUC.69617 UREA 10%complete repair lotion','LR HYALU B5 CR+ HYALU B5 SERUM','CALMTU NIGHT CPSX15','SENSILAB lizavchinja za patuvanje x 3','MUSTELA derm.gel za mienje novorod. 500 ml','MUSTELA HRANLIV COLD KREM ZA LICE 40ML','MUSTELA KREMA PROTIV STRII 150ML','MUSTELA zastiten vitaminski krem 100 ml','JAM-VIT.C 500mg+D3 500IE TBL.X75','INN-DIART SPRIC 1,8% 2ML','INN-FORTINN KESI X 30','INN-TENDOCILINN KESI X 28','ESI LE DIECI ERBE COLON CLEANSE tbl.x60','4U BIMUNAL SIR.300ML','LR- HYALU B5 SERUM+ RUMENILO','Curaprox Kids Watermelon','Curaprox Kids Strawberry','Curaprox Kids Mint','Curaprox BE YOU Watermelon 60ml','Curaprox BE YOU Peach 60ml','Curaprox BE YOU Grapefruit','Curaprox BE YOU Gin Tonic 60ml','Curaprox BE YOU Blackberry 60ml','Curaprox BE YOU Apple 60ml','Curaprox Baby четка за заби за деца','Curaprox CS 5460 Ortho четка за заби','Curaprox CPS 457 џебен сет','Curaprox CPS 011 Prime Start Зелено','Curaprox CPS 011 Prime Start Црвено','VICHY Capital Soleil воден флуид со заштитен фактор 50 за комбинирана до масна кожа','VICHY Capital Soleil UV-AGE DAILY тониран воден флуид против фото-стареење UVB SPF 50+ и UVA PF 46','ABBOTT Prosure високоенергетска и високопротеинска ентерална исхрана со вкус на банана','ABBOTT Prosure високоенергетска и високопротеинска ентерална исхрана со вкус на ванила','ABBOTT Prosure високоенергетска и високопротеинска ентерална исхрана со вкус на чоколадо','ABBOTT Prosure високоенергетска и високопротеинска ентерална исхрана со вкус на бобинки','VICHY Liftactive B3 серум 30ml','VICHY Liftactiv Vitamin C серум 20ml','LA ROCHE POSEY Toleriane Ultra Dermallergo серум','LA ROCHE POSEY Retinol B3 серум')
        ";

        $res = $this->query($sql);

        return $res;
    }

    public function restore_wc_data() {
        $this->log_file = plugin_dir_path(__FILE__) . "/sync.log";

        set_time_limit(0);
        
        $updated = 0;
        $untouched = 0;
        $not_found = 0;

        $old_products = $this->helper->csv_to_array(LIFELINE_PLUGIN_DIR . 'src/wc.csv');
        
        $args = array(
            'status' => 'publish',
            'orderby' => 'title',
            'order' => 'ASC',
            'limit' => 100,
            'offset' => 0
        );

        $products_count = wc_get_products(array( 'limit' => -1 )); 
        
        $pages = ceil(count($products_count) / $args['limit']);

        if ($pages > 0) {
            require_once(ABSPATH . 'wp-admin/includes/media.php');
            require_once(ABSPATH . 'wp-admin/includes/file.php');
            require_once(ABSPATH . 'wp-admin/includes/image.php');
        }

        $paging = new stdClass();
        $paging->count = count($products_count);
        $paging->pages = $pages;
        
        for ($i = 0; $i < $pages; $i++) {
            $args['offset'] = $args['limit'] * $i;

            $products = wc_get_products($args);
            
            $count = 1;

            $paging->offset = $args['offset'];
            $paging->page = $i;

            foreach ($products as $product) {
                $found = array_filter($old_products, function($old) use ($product) {
                    return strtolower($old->Name) == strtolower($product->get_name());
                });

                if (count($found)) {
                    $old_product = current($found);

                    $product_id = $product->get_id();

                    $img_update = !empty($old_product->Images) && empty($product->get_image_id());
                    $desc_update = !empty($old_product->Description);
                    $short_desc_update = !empty($old_product->ShortDescription);

                    if ($img_update) {
                        $img_upload = wc_rest_upload_image_from_url($old_product->Images);
                        $image_id = wc_rest_set_uploaded_image_as_attachment($img_upload, $product_id);

                        // $image_id = media_sideload_image($old_product->Images, $product_id, basename($old_product->Images));
                        $product->set_image_id($image_id);
                        // set_post_thumbnail( $product_id, $thumbnail_id );
                    }
                    
                    if ($desc_update)
                        $product->set_description($old_product->Description);

                    if ($short_desc_update)
                        $product->set_short_description($old_product->ShortDescription);

                    if ($img_update || $desc_update || $short_desc_update) {
                        $product->save();

                        $updated++;
                    } else {
                        $untouched++;
                    }
                }
                else {
                    $not_found++;
                }

                $this->set_status($paging, $count);

                $count++;
            }
        }

        $log_data = [
            'inserted' => $untouched,
            'updated' => $updated,
            'deleted' => $not_found,
            'logs' => 'Old data restored.',
            'old_restore' => 1
        ];

        $this->log($log_data);

        if (file_exists(LIFELINE_PLUGIN_DIR . 'src' . DIRECTORY_SEPARATOR . 'wc.csv'))
            @unlink(LIFELINE_PLUGIN_DIR . 'src' . DIRECTORY_SEPARATOR . 'wc.csv');

        $this->remove_status_file();

        return $log_data;
    }

    public function count() {
        $count_sql = "SELECT COUNT(sifra) FROM $this->view";
        $count = $this->query($count_sql);

        return sizeof($count) > 0 ? $count[0]->count : 0;
    }

    public function get_products($limit, $offset) {
        $sql = "SELECT * FROM $this->view LIMIT $limit OFFSET $offset";

        return $this->query($sql);
    }

    public function get_taxes() {
        $sql = "SELECT DISTINCT(ddv) FROM $this->view";

        return $this->query($sql);
    }

    public function sync_taxes() {
        // WC_Cache_Helper::invalidate_cache_group( 'taxes' );
        // WC_Cache_Helper::get_transient_version( 'shipping', true );

        $taxes = $this->get_taxes();

        $location = array( 'country' => '', 'state' => '', 'city' => '', 'postcode' => '' );

        foreach ($taxes as $tax) {
            $int_tax = intval($tax->ddv);
            $float_tax = floatval($tax->ddv);

            $tax_rate_data = array(
                'tax_rate_country' => '*',
                'tax_rate_state' => '*',
                'tax_rate' => $float_tax,
                'tax_rate_name' => "$int_tax",
                'tax_rate_priority' => 1,
                'tax_rate_compound' => 0,
                'tax_rate_shipping' => 1,
                'tax_rate_order' => 0,
                'tax_rate_class' => $this->tax_classes["$int_tax"]
            );
            
            WC_Tax::_insert_tax_rate( $tax_rate_data );
        }
    }

    public function sync($type = self::SYNC_TYPE_UNKNOWN) {
        $this->log_file = plugin_dir_path(__FILE__) . "/sync.log";

        set_time_limit(0);

        $inserted = 0;
        $updated = 0;
        $deleted = 0;

        // $this->sync_taxes();
        // $taxonomy_id = $this->set_attribute('brand');
        
        $count = $this->count();

        if ($count == 0) {
            $error_data = [
                'inserted' => $inserted,
                'updated' => $updated,
                'deleted' => $deleted,
                'logs' => 'No products in database or no connection to database server',
                'old_restore' => 0, 
                'sync_type' => $type
            ];

            $this->log($error_data);
            return $error_data;
        }

        $pages = ceil($count / $this->limit);

        $offset = 0;

        $responses = [];

        $paging = new stdClass();
        $paging->count = $count;
        $paging->pages = $pages;

        // collect skus for later deletion
        $product_skus = [];

        for ($i = 0; $i < $pages; $i++) {
            $offset = $i == 0 ? $offset : $offset + $this->limit;

            $products = $this->get_products($this->limit, $offset);

            $paging->offset = $offset;
            $paging->page = $i;
            
            $responses[] = $this->import($products, $paging, $product_skus);
        }

        foreach ($responses as $response) {
            $inserted += $response->inserted;
            $updated += $response->updated;
            // $deleted += $response->deleted;
        }

        $deleted = $this->check_and_delete_products($product_skus);

        $log_data = [
            'inserted' => $inserted,
            'updated' => $updated,
            'deleted' => $deleted,
            'logs' => 'Synchronization successful',
            'old_restore' => 0, 
            'sync_type' => $type
        ];

        $this->log($log_data);

        $this->remove_status_file();
        
        return $log_data;
    }

    public function async_sync() {
        $results = $this->sync(self::SYNC_TYPE_MANUAL);

        $return = new stdClass();

        $return->success = true;
        $return->results = $results;

        echo json_encode($return);

        wp_die();
    }

    public function async_restore() {
        $results = $this->restore_wc_data();

        $return = new stdClass();

        $return->success = true;
        $return->results = $results;

        echo json_encode($return);

        wp_die();
    }

    public function async_status() {
        $return = new stdClass();

        $return->success = true;
        $return->status = ceil($this->get_status());

        echo json_encode($return);

        wp_die();
    }

    public function import($products, $paging, &$product_skus) {
        $return = new stdClass();
        $return->inserted = 0;
        $return->updated = 0;
        $return->deleted = 0;

        $count = 1; 

        foreach($products as $i => $product) {
            $product_id = wc_get_product_id_by_sku($product->sifra);

            if (is_numeric($product_id) && $product_id > 0)
                $return->updated++;
            else 
                $return->inserted++;

            $woo_product = $product_id == 0 || !$product_id ? new WC_Product_Simple() : wc_get_product($product_id);

            $woo_product->set_name($product->naziv);
            $woo_product->set_sku($product->sifra);
            $woo_product->set_regular_price($product->maloprodazna);
            $woo_product->set_price($product->maloprodazna);
            $woo_product->set_description($product->opis);
            $woo_product->set_manage_stock(true);
            $woo_product->set_stock_quantity($product->zaliha);
            $woo_product->set_stock_status($product->zaliha > 0 ? 'instock' : 'outofstock');
            
            $attribs = $this->add_attribute_value('Manufacturer', $product->proizvoditel);
            
            $woo_product->set_attributes($attribs);

            $ddv = (int) $product->ddv;
            $woo_product->set_tax_class($this->tax_classes["$ddv"]); // standard

            $woo_product->set_status('publish');

            $product_id = $woo_product->save();

            $product_skus[$product->sifra] = $product_id;

            $this->set_terms($attribs, $product_id);

            $this->set_status($paging, $count);

            $count++;
        }

        return $return;
    }

    private function check_and_delete_products($skus) {
        $empty_skus = [];

        foreach($skus as $key => $value){
            if(!empty($value))
                $empty_skus[] = $value;
        }

        $products = new WP_Query(
            [
                'post_type'  => [ 'product' ],
                'post_status' => 'publish',
                'posts_per_page' => -1,
                'paged' => 1,
                'post__not_in' => $empty_skus
            ]
        );

        $deleted = 0;

        while($products->have_posts()) : $products->the_post();
            $product = wc_get_product($products->post->ID);
            $product->delete();

            $deleted++;
        endwhile;

        return $deleted;
    }

    private function set_terms($attribs, $product_id) {
        foreach ($attribs as $attrib) {
            $tax = $attrib->get_name();
            $vals = $attrib->get_options();

            $termsToAdd = array();

            if (is_array($vals) && count($vals) > 0) {
                foreach ($vals as $val) {
                    //Get or create the term if it doesnt exist:
                    $term = $this->get_attribute_term($val, $tax);

                    if ($term['id']) $termsToAdd[] = $term['id'];
                }
            }

            if (count($termsToAdd) > 0)
                wp_set_object_terms($product_id, $termsToAdd, $tax, true);
        }
    }

    private function create_global_attribute($name) {
        $slug = wc_sanitize_taxonomy_name($name);        
        $taxonomy_name = wc_attribute_taxonomy_name( $slug );

        if (taxonomy_exists($taxonomy_name))
            return wc_attribute_taxonomy_id_by_name($slug);

        $attribute_id = wc_create_attribute( array(
            'name'         => $name,
            'slug'         => $slug,
            'type'         => 'select',
            'order_by'     => 'menu_order',
            'has_archives' => false,
        ) );

        //Register it as a wordpress taxonomy for just this session. Later on this will be loaded from the woocommerce taxonomy table.
        register_taxonomy(
            $taxonomy_name,
            apply_filters( 'woocommerce_taxonomy_objects_' . $taxonomy_name, array( 'product' ) ),
            apply_filters( 'woocommerce_taxonomy_args_' . $taxonomy_name, array(
                'labels'       => array(
                    'name' => $name,
                ),
                'hierarchical' => true,
                'show_ui'      => false,
                'query_var'    => true,
                'rewrite'      => false,
            ) )
        );

        //Clear caches
        delete_transient( 'wc_attribute_taxonomies' );

        return $attribute_id;
    }

    private function add_attribute_value($name, $value) {
        $attributes = array();

        $attribute = new WC_Product_Attribute();
        $attribute->set_id( 0 );
        $attribute->set_position(0);
        $attribute->set_visible( true );
        $attribute->set_variation( true );

        //Look for existing attribute:
        $existingTaxes = wc_get_attribute_taxonomies();

        //attribute_labels is in the format: array("slug" => "label / name")
        $attribute_labels = wp_list_pluck( $existingTaxes, 'attribute_label', 'attribute_name' );
        $slug = array_search( $name, $attribute_labels, true );

        if (!$slug) {
            //Not found, so create it:
            $attribute_id = $this->create_global_attribute($name);
        }
        else {
            //Otherwise find it's ID
            //Taxonomies are in the format: array("slug" => 12, "slug" => 14)
            $taxonomies = wp_list_pluck($existingTaxes, 'attribute_id', 'attribute_name');

            if (!isset($taxonomies[$slug]))
                return [];

            $attribute_id = (int)$taxonomies[$slug];
        }

        $taxonomy_name = wc_attribute_taxonomy_name($slug);

        $attribute->set_id($attribute_id);
        $attribute->set_name($taxonomy_name);
        $attribute->set_options([ $value ]);

        $attributes[] = $attribute;


        return $attributes;
    }

    public function get_attribute_term($value, $taxonomy) {
        //Look if there is already a term for this attribute?
        $term = get_term_by('name', $value, $taxonomy);

        if (!$term) {
            //No, create new term.
            $term = wp_insert_term($value, $taxonomy);

            if (is_wp_error($term)) 
                return array('id'=>false, 'slug'=>false);

            $termId = $term['term_id'];
            $term_slug = get_term($termId, $taxonomy)->slug; // Get the term slug
        }
        else {
            //Yes, grab it's id and slug
            $termId = $term->term_id;
            $term_slug = $term->slug;
        }

        return ['id' => $termId, 'slug' => $term_slug];
    }

    private function set_status($paging, $current) {
        if (!$this->log_file)
            $this->log_file = plugin_dir_path(__FILE__) . "/sync.log";

        $stat_file = fopen($this->log_file, "w") or die("Unable to open sync file!");

        $current = $paging->offset + $current;

        $percentage = (($current / $paging->count) * 100);

        fwrite($stat_file, $percentage);

        fclose($stat_file);
    }

    private function get_status() {
        if (!$this->log_file)
            $this->log_file = plugin_dir_path(__FILE__) . "/sync.log";

        $stat_file = fopen($this->log_file, "r") or die("Unable to open sync file!");

        if (filesize($this->log_file) > 0) {
            $content = fread($stat_file, filesize($this->log_file));

            fclose($stat_file);
    
            return $content;
        }
        
        return 0;
    }

    private function remove_status_file() {
        if (!$this->log_file)
            $this->log_file = plugin_dir_path(__FILE__) . "/sync.log";

        @unlink($this->log_file);
    }
}